### ISSUE TITLE
[Suggestion] RF Support

### ISSUE THREAD

**Issue by ghost** [Thutmose/Thut#10]
Thought I'd post my suggestion here just to keep a record of it and others can chime in with support if they wish.

It would be nice if the elevators had RF support - My modpack and likely many others use RF as the main power system. Perhaps an RF controller or something? I'm willing to help with ideas/code if you need it.

Thanks for your consideration and love the mod!

**Comment by Squirtle8459** [comment]
this would be a nice addition, just simply having an RF network attached to the controller and it consistently drains a fixed amount of RF and if the RF drained doesn't match the requirements the screen goes Blank or has a 'NOT Powered' displayed on it... as stated by @Nentify if needed I can assist with the RF API if you are unfamiliar with it and need some assistance..

**Comment by Thutmose** [comment]
eh, I don't ever plan to use RF again, I will probably get around to fixing the Tesla support shortly, I can also add in Forge Energy support, those two are much better written APIs for power use.

**Comment by Thutmose** [comment]
forge energy should be inherently supported by RF, so whenever I get power re-enabled, that should work too
