### ISSUE TITLE
[1.12.2] Manual recipe not working

### ISSUE THREAD

**Issue by LiskoSlayer63** [Thutmose/Thut#101]
The manual book can't be crafted with the instructions it says through JEI.

**Thut's Elevators version:** 6.0.14
**ThutCore version:** 5.16.1
**Forge version:** 14.23.1.2586
**Minecraft version:** 1.12.2

**Comment by themechman** [comment]
Can confirm this is not working. used to be crafted with linker remote and book. Had to console give to player.

**Comment by Thutmose** [comment]
works in current versions: 
![image](https://user-images.githubusercontent.com/2363472/44614596-c6dd0600-a7f5-11e8-96e4-6b31420204bf.png)
