### ISSUE TITLE
[1.12.2] Error flood when used on a server

### ISSUE THREAD

**Issue by LiskoSlayer63** [Thutmose/Thut#102]
My friend built an elevator on our server and when he tried it the server console was flooded by errors. i managed to copy the error spam and uploaded it [here](https://pastebin.com/deUvUnRX). This flooding caused the whole server to freeze and finally everyone got kicked out.

This might be same as #96.

**Thut's Elevators version:** 6.0.14
**ThutCore version:** 5.16.1
**Forge version:** 14.23.1.2586
**SpongeForge version:** 2555-7.1.0-BETA-2890
**Minecraft version:** 1.12.2

**Comment by Thutmose** [comment]
looks like it is the same as #96, I will test some fixes, and hopefully have an update out shortly

**Comment by Thutmose** [comment]
6.0.15 is uploaded, it should fix this issue, re-make the issue if it doesn't.
