### ISSUE TITLE
[Suggestion]Floor Indicator

### ISSUE THREAD

**Issue by ghost** [Thutmose/Thut#103]
Hi,
I have been playing around with your mod for quite a while now, and its sick!
But, could you possibly add a Floor Indicator to the mod, to tell you witch floor the elevator is on
for now, im using a elevator controller with a barrier in front of it :P

**Comment by Thutmose** [comment]
I am planning on some additional features for blocks, this is a good suggestion, I will look into it when I get time to look into the block stuff.

**Comment by Thutmose** [comment]
there are floor indicators in recent versions
