### ISSUE TITLE
Thutcore crashed with latest forge (server)

### ISSUE THREAD

**Issue by lebanni** [Thutmose/Thut#104]
forge-1.12.2-14.23.2.2619-universal.jar
thutcore-1.12.2-5.16.1.jar

[crash-2018-02-27_13.54.35-server.txt](https://github.com/Thutmose/Thut/files/1762986/crash-2018-02-27_13.54.35-server.txt)

**Comment by Thutmose** [comment]
hmm, forge must have changed where some things are loaded, that was never called on server before.  Hopefully this weekend I will have time to look into fixing this.

**Comment by lebanni** [comment]
Seems like issue not happening any more with recents forge versions. Sorry for the inconvenience.

**Comment by Thutmose** [comment]
ya, looking more carefully at this bug, it seems like it might have been forge screwing something up with that specific forge version, I cant find anywhere I could be causing this, so will close this issue, open a new one if it happens again.
