### ISSUE TITLE
Suffocation Damage Taken when a wall is next to the elevator.

### ISSUE THREAD

**Issue by WenXin20** [Thutmose/Thut#11]
#### What happens:

Suffocation Damage
#### Steps to reproduce:
1. Make an elevator, with a wall on the corner.
2. Walk to the wall and start to take damage.

---
#### Affected Versions:
- Thut Core: 3.1.8
- Thut's Elevators (If Applicable): 3.0.9
- Forge: 2026-1.10.2
  ![2016-08-04_14 45 14](https://cloud.githubusercontent.com/assets/12000593/17416051/184e8412-5a52-11e6-8f55-9a1a9a4d80f0.png)

**Comment by WenXin20** [comment]
Has this been looked at or fixed?

**Comment by Thutmose** [comment]
I am not sure, I have been dealing with the disappearing ones, some of the collision code was changed recently, see if it has?

**Comment by WenXin20** [comment]
Ok, I'll let you know

**Comment by WenXin20** [comment]
Yep, I still take suffocation damage.

**Comment by Thutmose** [comment]
Ok, I will look into getting this fixed now then.

**Comment by WenXin20** [comment]
Thanks

**Comment by Thutmose** [comment]
I Think I have found the cause if the issue, I am working on fix now.

**Comment by Thutmose** [comment]
Testing fix for this now, then I will upload new version of ThutCore which fixes it.

**Comment by Thutmose** [comment]
This has been fixed, will upload ThutCore 3.4.2 and Thuttech 4.0.5 which fix it shortly.

**Comment by Thutmose** [comment]
Uploaded those to curse. closing this issue.

**Comment by WenXin20** [comment]
Thanks
