### ISSUE TITLE
Serverlog spam

### ISSUE THREAD

**Issue by TheRealDadbeard** [Thutmose/Thut#112]
My Console window gets spammed by this: https://pastebin.com/e46NeQj5

Edit: Seems debug mode was somehow enabled in thutcore who knows why.

**Comment by Thutmose** [comment]
this is a debug print that I had for testing a datafixer, that I forgot to remove/disable before compiling, it is in the elevator mod, will be removed for next release

**Comment by Thutmose** [comment]
This spam should be gone in current release
