### ISSUE TITLE
Can't remove or edit elevators after loggin back in on server

### ISSUE THREAD

**Issue by TheRealDadbeard** [Thutmose/Thut#113]
Title. Created an elevator but after logging out of the server and back in I can't do anything with it. The remote does not work and the stick too. Sometimes happens after teleporting  too. No message nothing, no error in server console, nothing on client either.

Going into Creative mode lets me remove it. Issue other players on the server don't have that luck-

thuttech-1.12.2-6.1.2
thutcore-1.12.2-5.19.4

**Comment by Thutmose** [comment]
I will look into this, sounds like something is going wrong with owner saving/loading

**Comment by GameBurrow** [comment]
Can confirm similar thing. Didn't play for several days on my server (reinstalled windows) after returning was unable to do anything with the elevator.

**Comment by CrazyCowboy557** [comment]
I've heard from players on my server having the same issue.

**Comment by Thutmose** [comment]
I have finally been able to get time to find and fix this bug, it should be fixed in next version.
