### ISSUE TITLE
Crash while running with latest Elevator Mod from Thutmose

### ISSUE THREAD

**Issue by Grrpapa** [Thutmose/Thut#115]
[crash-2018-08-26_10.36.02-client.txt](https://github.com/Thutmose/Thut/files/2321650/crash-2018-08-26_10.36.02-client.txt)

**Comment by Thutmose** [comment]
6.1.4 should be released shortly with the fix for this

**Comment by Grrpapa** [comment]
Thank you.  I really enjoy using your elevators in MC.  This is the best mod I use.  Your work is excellent

**Comment by Grrpapa** [comment]
Thank you.  I really enjoy using your elevators in MC.  This is the best mod I use.  Your work is excellent
