### ISSUE TITLE
2.1 [1.7.10] Elevator refuses to go underground + No crafting recipes for certain items

### ISSUE THREAD

**Issue by StoicSirius** [Thutmose/Thut#117]
#### What happens: 
**1.** The elevator refuses to go underground. It grounds to a halt several blocks in if I try to make it go from the surface, and doesn't move at all if it's already underground. I tried widening the hole, make the elevator smaller, dig a hole to the surface; nothing worked.
**2.** Recipes seem to be absent for every item beside the dusts, brushes, and rebar.

#### What you expected to happen: 
The obvious.

#### Steps to reproduce: 
Make an elevator that goes underground. 
Try to craft any of the items
____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutcore: N/A since it's only needed for versions 1.8.9+
- Minecraft: 1.7.10
- Forge: idk, I use a launcher that has a list of versions with forge, optifine, and liteloader (TLauncher)

Playing with a custom modpack.

**Comment by Thutmose** [comment]
1.7.10 has been unsupported for 3 years or so now, so nothing I can do about this. 

You might be able to add recipes for things with some other mod, and check your rails and nearby blocks for the underground stuff?

**Comment by StoicSirius** [comment]
I dug a huge hole bigger than the elevator. The problem persists

**Comment by Thutmose** [comment]
in which case my only suggestion is to update to 1.12.2, the mod was re-written for modern versions of minecraft, and I will try to fix any bugs that are found for the supported version

**Comment by StoicSirius** [comment]
Sadly, that would not be possible. Not just because I don't want to, but also because the owner of the server I'm playing on is tired of restarting our survival every single time something goes wrong.
Guess I'll find another mod or I'll just resort to viaducts...
edit: Thank you for the help anyway.
