### ISSUE TITLE
Add a "How to camouflage the Controller Block" to the Manual book.

### ISSUE THREAD

**Issue by Griefed** [Thutmose/Thut#125]
Title. 
A friend of me discovered by accident that it's possible to camouflage the elevator controller blocks. After going through google and not finding anything, I checked on your discord server and found the answer there:
"The controllers can be disguised by right clicking their bottom faces with a block"
It may need a block update, i.e. placing a block next to it will cause the texture to update.
![camouflage](https://user-images.githubusercontent.com/44273438/47175954-b6886980-d314-11e8-8481-43df143c1404.PNG)

It would be awesome to have an explanation on how that is done in the manual. 
Thanks!

Cheers,
Griefed

**Comment by timmit99** [comment]
Oh my god... THANK you.. i have been looking to figure this out for HOURS. Even a simple book to the mod would be helpful.

**Comment by Griefed** [comment]
If memory serves, there's a manual for the mod. Check JEI/NEI. As far as I am aware though, it doesn't tell you how to camouflage the blocks, though. Hence my post here on Github. :)

Anyway, glad I could help!

**Comment by timmit99** [comment]
AS far as i can tell searching "@thut" in JEI only shows 3 items: Device Linker, Elevator, and Elevator Controller Block. This is version `thuttech-1.12.2-6.1.6.jar` which was released 5/18/19 so it seems to be the latest version
