### ISSUE TITLE
[Suggestion] Rewrite ThutTech Manual so it's part of the mod, not minecraft:written_book

### ISSUE THREAD

**Issue by Griefed** [Thutmose/Thut#126]
Main reason being the fact that the current manual can't be integrated into the Akashic Tome (https://minecraft.curseforge.com/projects/akashic-tome). If a modpack has several mods that each provide a manual/lexicon/guide etc., it becomes easy to clutter your inventory or loose the overview of which is which. Akashic Tome kinda solves that problem by allowing the player to combine them all into one giant tome.
![akashic_tome](https://user-images.githubusercontent.com/44273438/47609181-2a73f180-da3a-11e8-86d2-b8bd8b90a8db.png)

I configured a start loadout which every player of my modpack gets when they first load into a world/server, said loadout includes an Akashic tome containing all the manuals/guides/lexicons etc. and I would love to include the ThutTech Manual as well.
![akashic_tome_integration_of_other_books](https://user-images.githubusercontent.com/44273438/47609180-1b8d3f00-da3a-11e8-841c-6b3219398108.png)
![akashic_tome_contents](https://user-images.githubusercontent.com/44273438/47609176-0fa17d00-da3a-11e8-8cf4-1cc2f3b6f028.png)

It would also look a lot nicer if it read:
ThutTech Manual
by Thutmose
Thut's Elevators (this says Minecraft currently)
![thuttech_manual](https://user-images.githubusercontent.com/44273438/47609167-dc5eee00-da39-11e8-8886-f7b7e249e445.png)

If it's too annoying, then go ahead and close this issue. It's not important, it's basically just a cosmetic and convenience thing. 
I love your mod and would love to see this change, but understand if it's not worth the hassle.

Thank you for your time and have a nice day!

Cheers,
Griefed

**Comment by JakeCWolf** [comment]
This has also created a conflict in FTB Revelations, making the book uncraftable, even with the Forestry Worktable which can cycle through conflicting recipes.

**Comment by rogama25** [comment]
It will be even better if it's also translatable through the .lang file.
