### ISSUE TITLE
Gamecrash

### ISSUE THREAD

**Issue by david15557** [Thutmose/Thut#127]
The game crashes.

When i try to link an elevator the game freezes for a second and then crashes. The log says this: "The game crashed whilst unexpected error
Error: java.lang.NoSuchMethodError: thut.lib.CompatWrapper.getStackSize(Lnet/minecraft/item/ItemStack;)I"

#### Steps to reproduce:

1. Build an elevatorplatform
2. Add  the computer and stuff.
3. Link the elevator.
And then it crashes.

____
- Thutcore: 
- Minecraft: 1.12.2
- Forge:

**Comment by Thutmose** [comment]
Update your mods.
