### ISSUE TITLE
[1.10.2] Ticking Entity Crash

### ISSUE THREAD

**Issue by mzx987** [Thutmose/Thut#13]
This suddenly started to happen after coming back from the Nether (I've been there several times before, and it never decided to this until now).

Long story short, after going through the portal out of the Nether world and into the Overworld, I noticed the Elevator Control blocks in my structure were "missing". When I walked right on top of it, the server crashed. I had to remove the mod to even get the server working again.

Here is the crash report that kept appearing every time I reset the server and tried to join (this log appears for both the server and the client):
http://pastebin.com/g3FUgdCq

**Comment by Thutmose** [comment]
Hmm, I will try to get this fixed shortly.

**Comment by Thutmose** [comment]
I was in the middle of writing in chest support for the lifts, so it might be a day or two before I get a release that fixes this.

**Comment by mzx987** [comment]
Alrighty. Thanks for the quick response.

**Comment by Thutmose** [comment]
This issue has been fixed for the next version, I will hopefully get it out sometime this weekend, it has been a major re-write of things, so I am currently trying to decide on how to redo some things.

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions
