### ISSUE TITLE
Game crash when loading a world

### ISSUE THREAD

**Issue by WhiteScorpion7** [Thutmose/Thut#130]
When I place Thut's blocks in a world, after a few minutes the game crashes. Then crash happens every time when I try to load the world. This is the report:

[crash-2019-01-23_19.26.33-server.txt](https://github.com/Thutmose/Thut/files/2789056/crash-2019-01-23_19.26.33-server.txt)

When I remove all other mods and resourcepacks nothing changes. But in my another modpack everything works fine.

**Comment by Thutmose** [comment]
That is odd, I wonder how a player got assigned as an elevator... I can have that fixed for next update.

In this particular case, the elevator controller block located at (0,63,-35) has somehow been told that your player is the elevator it is linked to.

That bug should only affect that particular world, and if you remove the mod, then place say stone over where the elevator controller was, then re-add the mod, it should fix that issue.

**Comment by WhiteScorpion7** [comment]
Ok, I try it. Thanks.
