### ISSUE TITLE
Minecraft Closes

### ISSUE THREAD

**Issue by Simufreak** [Thutmose/Thut#131]
#### Issue Description:
When I try to load a Map Minecraft crashes one second after entering it

#### Steps to reproduce:
Restart mnecraft

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutcore:  5.19.9
- Minecraft: 1.12.2
- Forge:14.23.0.2529
[crash-2019-02-12_09.22.45-server.txt](https://github.com/Thutmose/Thut/files/2854768/crash-2019-02-12_09.22.45-server.txt)

**Comment by Thutmose** [comment]
your thuttech version is way outdated, you can find the current version here:

https://minecraft.curseforge.com/projects/thuts-elevators/files

Your minecraft forge version is also way outdated, you can find a current version here:

http://files.minecraftforge.net/

Try updating those and see if it still crashes, if it does, please make a issue with the updated crash report.
