### ISSUE TITLE
Error floor [BUG]

### ISSUE THREAD

**Issue by Maciek21** [Thutmose/Thut#132]
#### What happens:
When I'm trying to connect Elevator, controller block and floor with device linker I click on controller block and there are two red points. I cannot choose floor to assign.

____
#### Affected Versions:

- Thutcore: 5.19.9
- Minecraft: 1.12.2
- Forge: 14.23.5.2814
![2019-03-04_16 43 07](https://user-images.githubusercontent.com/48216130/53744176-c1473380-3e9c-11e9-9378-a25e872560b5.png)

**Comment by Thutmose** [comment]
you have the controller in edit mode, shift right click it with an un-linked linker to get it back into floor mode.
