### ISSUE TITLE
The mod doesnt work

### ISSUE THREAD

**Issue by Amalekita** [Thutmose/Thut#133]
Hello ive been trying to use the Elevator mod but any version i choose just doesnt work iam using the Minecraft version 1.11.2 and nearly every time i put a mod version for this minecraft version in the mod blocks arent in the game i tried to manually craft them and to find the in the creative inventory but they are  just not there.
![Unbenannt](https://user-images.githubusercontent.com/48621958/54475498-30ece500-47f2-11e9-88b9-a38e5b6fa742.png)
 

or this happends 
![grafik](https://user-images.githubusercontent.com/48621958/54475641-e704fe80-47f3-11e9-8686-ec505d831fd3.png)

**Comment by Thutmose** [comment]
Please include the versions of thutcore and thuttech that you are trying to use, as well as the versions of forge.

**Comment by Amalekita** [comment]
I fixed it. I didnt notice that the mod needs 2 parts that was the reason it didnt function but thanks for the help i wish you a good day.
