### ISSUE TITLE
Right click when creating elevator crashes game

### ISSUE THREAD

**Issue by thatfalloutguy784** [Thutmose/Thut#135]
I have some mods installed, perhaps one is interfering with it? I don't know how to find bugs in a crash report so don't really expect me to see the problem right away.

[crash-2019-03-26_00.52.02-client.txt](https://github.com/Thutmose/Thut/files/3006819/crash-2019-03-26_00.52.02-client.txt)

**Comment by Thutmose** [comment]
Update your elevator mod, the version you are using is missmatched with your thutcore
