### ISSUE TITLE
OP commands

### ISSUE THREAD

**Issue by knoxhack** [Thutmose/Thut#14]
All players can see op commands and also can switch to cheat mode with JEI

https://github.com/MinecraftModDevelopment/MMD-Dev-Server/issues/193

**Comment by Thutmose** [comment]
hmm, I should have put a larger warning on the allowUse config option for ThutPerms.  If you disable that, it should fix this issue (but then non-op players will not be able to use op commands even if their group has permissions to do so).

allowUse internally sets the boolean that vanilla uses to ignore OP permissions, I will see if I can detect command use from non-standard sources.  

Do you know if the JEI cheat mode gives the items via a command, or does it just check the canCommandSenderUseCommand thing?

What I guess I could try to see if I can intercept the message sending before, and only set it to allow all use if it is from a command, or a chat message typed, I am not sure if that will be possible though.

**Comment by Thutmose** [comment]
the mod for this has moved repo, so no longer valid here, iirc the JEI issue was fixed on JEI side though
