### ISSUE TITLE
[1.10.2] Elevators tend to move in a different direction

### ISSUE THREAD

**Issue by mzx987** [Thutmose/Thut#15]
I'm currently using the latest stable version released (thuttech 4.0.2).

From what I noticed, if the elevator is hugging against any walls while reaching its destination, it will suddenly phase through ~10 blocks away.

**Comment by Thutmose** [comment]
ahha, that is how that happens, once I get it happening on my end, I can get it fixed.  Hopefully I can get around to try to fix this tonight.

**Comment by mzx987** [comment]
Alrighty. Thanks again!

**Comment by Thutmose** [comment]
Can you see if this still occurs in 4.0.3? I think it might have been caused by them trying to take damage, and being thrown out through walls, that should now be dealt with.

I also fixed the issue with not being able to link to controllers from inside the lift itself.

**Comment by mzx987** [comment]
I'll test this out here soon. It may take a few hours before I can do so.

**Comment by Thutmose** [comment]
This should now be fixed properly in 4.0.4, seems the issue was related to using elevators with an even number of blocks on a side, it should now be fixed.
