### ISSUE TITLE
Elevator lands 2 blocks from shaft

### ISSUE THREAD

**Issue by MishaOpstal** [Thutmose/Thut#150]
Elevator not landing at right spot after travel, during travel weird things happen

This video will explain the issue:
[Thut's Elevator Failure](https://onthelink.nl/thutsfailedme.mp4)

____

- Thuttech: thuttech-1.12.2-6.1.6
- Thutcore: thutcore-1.12.2-5.21.0
- Minecraft: 1.12.2
- Forge: 1.12.2-forge1.12.2-14.23.5.2838

**Comment by Thutmose** [comment]
Possibly an issue from an un-tested case of 2x3 elevators, can you include the coordinates of the elevator? I will look into fixes.

**Comment by MishaOpstal** [comment]
ofcourse, i'll send them when i get home, sry for my late reply
