### ISSUE TITLE
Invisible Blocks?

### ISSUE THREAD

**Issue by RobertLSnead** [Thutmose/Thut#16]
The elevator is now invisible(can not see) with the latest update 4.0.5 with core 3.5.2!  It also is happening with malisisdoors 5.1.1 with core 4.2.2!

**Comment by Thutmose** [comment]
does it happen to any elevator you make, or just some? also are there any errors in console?

**Comment by RobertLSnead** [comment]
Every existing or new elevator, recreating has no change!  Have not confirmed client yet only affected on server!  Testing client now!
EDIT:  Client is also affected!

**Comment by Thutmose** [comment]
is anything spamming in console when it is invisible? also check if you can see where it should be with f3+b, that should outline it with a white box

**Comment by RobertLSnead** [comment]
I could not see any console spamming, hit box shows just fine!  Works and rides fine, just invisible!

**Comment by RobertLSnead** [comment]
The glitch is also affecting storage network as well.

**Comment by Thutmose** [comment]
hmm, what blocks are on (made into) the elevator?

**Comment by RobertLSnead** [comment]
One of the diamond chisel blocks, purple sky I believe.

**Comment by RobertLSnead** [comment]
I am going to try and remove malisis doors and see if that might be the culprit!
EDIT:
NO NEED!  It does appear to only affect chisel blocks, minecraft default blocks are working just fine!

**Comment by RobertLSnead** [comment]
I should add that the chisel mod was just updated to Chisel-MC1.9.4-0.0.6.48 and is causing all these issues!

**Comment by Thutmose** [comment]
I will look into it and see if I can find out what is going wrong with chiseled blocks in the elevators then.

**Comment by RobertLSnead** [comment]
Sounds good!  The author of chisels is looking into the issue as well!

**Comment by P3rf3ctXZer0** [comment]
Invisible blocks confirmed.

**Comment by Thutmose** [comment]
not sure why the above commit log didn't close this issue...
