### ISSUE TITLE
Elevators crash 1.14.4 with or without other mods present

### ISSUE THREAD

**Issue by traveldesign** [Thutmose/Thut#161]
Every time I try to make an elevator, the game crashes. I have two crash reports. The first is with all my other mods present and the second is just thutcore and the elevator mod present. 
[All of my mods present.txt](https://github.com/Thutmose/Thut/files/4137584/All.of.my.mods.present.txt)
[No other mods present.txt](https://github.com/Thutmose/Thut/files/4137585/No.other.mods.present.txt)

**Comment by traveldesign** [comment]
Ok the mod worked great with your fix but now that I've added my other mods back to the folder it crashed like before. I'm assuming it's a conflict with another mod. Here's the crash report. Any insight?
[New Elevator Crash Report.txt](https://github.com/Thutmose/Thut/files/4137693/New.Elevator.Crash.Report.txt)

**Comment by bluejorts** [comment]
I am also seeing a crash when creating an elevator, regardless of other mods. Using 1.15.2, happens with or without other mods present. I am seeing some console logs on startup indicating that the mod isn't receiving the block IDs it's expecting, not sure if that's related.

**Comment by Thutmose** [comment]
can you include the crash report from yours?

**Comment by Thutmose** [comment]
If this issue still occurs for 1.15.2, please re-make in https://github.com/Thuts-Mods/ThutTech/issues
