### ISSUE TITLE
The mod does not work well 1.7.10!

### ISSUE THREAD

**Issue by FireoNIS** [Thutmose/Thut#162]
## Read and then Delete this section - If this is in your bug report, it will be closed.
Any issues which report bugs, must fill out this form, otherwise they will be immediately closed with no response.
If your bug involves a crash, it *MUST* include a crash report. Failure to include the crash report without a good reason to not include it, will result in your issue being immediately closed.

#### Issue Description:
The mod then gives an error that Minecraft crashes, it is impossible to create elevator blocks! I would like the author to release a new release version of the mod on Minecraft 1.7.10 because Thut Elevators on 1.7.10 has not been released for a long time!

#### What happens:
The mod then gives an error that Minecraft crashes, it is impossible to create elevator blocks! I would like the author to release a new release version of the mod on Minecraft 1.7.10 because Thut Elevators on 1.7.10 has not been released for a long time!

#### What you expected to happen:
The mod then gives an error that Minecraft crashes, it is impossible to create elevator blocks! I would like the author to release a new release version of the mod on Minecraft 1.7.10 because Thut Elevators on 1.7.10 has not been released for a long time!

#### Steps to reproduce:

1.
2.
3.
...

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutcore: 2.0
- Minecraft: 1.7.10
- Forge:

**Comment by Thutmose** [comment]
this is not filled out correctly, 
also 1.7.10 has not been supported for half a decade or so.
