### ISSUE TITLE
doors not working when part of elevator

### ISSUE THREAD

**Issue by KickingAnimal** [Thutmose/Thut#163]
#### What happens:
open and close stade both render at the same time + collisions
![2020-02-16_16 45 14](https://user-images.githubusercontent.com/58342582/74608153-09c42500-50df-11ea-961d-62e9799b43de.png)

#### What you expected to happen: 
door opens/close

#### Steps to reproduce:

1. make elevator with door
2. open door

____
#### Affected Versions: 1.15.2-8.0.2 1.15.2-8.0.1 1.15.2-8.0.0

- Thutcore: 1.15.2-7.0.1
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.0

**Comment by Thutmose** [comment]
this feature hasn't been re-implemented in the 1.14.4/1.15.2 re-write

**Comment by Thutmose** [comment]
fixed: https://www.curseforge.com/minecraft/mc-mods/thutcore/files/2883915
