### ISSUE TITLE
Game crash when elevator contains "elevator  controller block"

### ISSUE THREAD

**Issue by KickingAnimal** [Thutmose/Thut#164]
#### Issue Description:
Game crash when elevator contains "elevator  controller block"

#### What happens:
when you make an elevator containing a "elevator controller block" the game crashes

#### What you expected to happen:
i expected the elevator to form and the game to not crash, maby that the controller would even work

#### Steps to reproduce:

1. build an structure with the controller block in it
2. make an elevator
3. crash
#### Log file
[crash-2020-02-16_23.15.57-server.txt](https://github.com/Thutmose/Thut/files/4211095/crash-2020-02-16_23.15.57-server.txt)

____
#### Affected Versions 1.15.2-8.0.2:

- Thutcore: 1.15.2-7.0.1
- Minecraft: 1.15.2
- Forge: 1.15.2-31.1.0

**Comment by Thutmose** [comment]
It seems some of the 1.14.4/1.15.2 re-write changes broke the controllers on the elevators, I will try to get this fixed, in the mean time, don't put controllers on the elevators.

**Comment by Thutmose** [comment]
fixed: https://www.curseforge.com/minecraft/mc-mods/thutcore/files/2883915

**Comment by KickingAnimal** [comment]
woah that was a fast fix, going to test it tomorrow
