### ISSUE TITLE
[Question] How to make bigger elevators?

### ISSUE THREAD

**Issue by FakeTheLoquender** [Thutmose/Thut#165]
## 

#### Issue Description: i just want to know how to make bigger elevators than 5x5x5.

**Comment by Thutmose** [comment]
increase the size options in the configs.

**Comment by FakeTheLoquender** [comment]
Where is that configs?

**Comment by FakeTheLoquender** [comment]
Im in 1.12.2, 6.1.6 version

**Comment by Thutmose** [comment]
thuttech.cfg, there is a maxRadius and maxHeight option which control these

**Comment by FakeTheLoquender** [comment]
I cannot find that file and dont know how to rewrite that

**Comment by Thutmose** [comment]
it is in the config folder...

**Comment by FakeTheLoquender** [comment]
Sorry, i dont knowed what you refered to configs folder, and thank you so much
