### ISSUE TITLE
Stained glass renders incorrectly

### ISSUE THREAD

**Issue by ghost** [Thutmose/Thut#166]
With the elevator mod. stained glass in a 3x3 elevator goes the colour of the stain except for one block. Normal glass stays clear.

Forge 14.23.5.2768, Thut Core 1.12.2-5.21.0, Thut's Elevators 1.12.2-6.1.6

Its always the same corner that stays clear, not dependent on which corner the linker selects first
![2020-03-02_21 56 06](https://user-images.githubusercontent.com/23115719/75772527-d5678e80-5d97-11ea-9d27-ce5845473f08.png)

**Comment by Thutmose** [comment]
I will try to get this looked into, hopefully by the weekend

**Comment by Thutmose** [comment]
If this issue still occurs for 1.15.2, please re-make in https://github.com/Thuts-Mods/ThutTech/issues
