### ISSUE TITLE
Can't find config in 1.15.2

### ISSUE THREAD

**Issue by Rosentti** [Thutmose/Thut#168]
#### Issue Description:
I want to make my elevators bigger, but I cannot find the config file to increase the size of the elevator.
It does not exist in the world folder or the old configs folder.

#### What happens:
No thuttech config file. Only thutcrafts config file in both the old config directory and the new config directory in the world folder.

#### What you expected to happen:
I expected to find a config file.

#### Steps to reproduce:

1.Look for a config file.
2.Do not find one.

____
#### Affected Versions (Do *not* use "latest"): Replace with a list of all mods you have in.

- Thutcore: 7.0.2
- Thut's elevators: 8.0.2
- Thutcrafts: 7.0.2

- Minecraft: 1.15.2
- Forge:31.1.18

**Comment by Thutmose** [comment]
where did you look? in the old config folder, it should be there in the folder called thuttech
