### ISSUE TITLE
Alternate Elevator Mode

### ISSUE THREAD

**Issue by Majora-Luna** [Thutmose/Thut#169]
Which can be toggled via config file (or control blocks if that wouldn't be a hassle) where instead of choosing a floor, when a player gets on an elevator, they get stuck/locked into it and can ascend or descend with jump and sneak.
Dismounting/exiting is achieved with any of the WASD/movement inputs (bonus: the player is automatically unhooked from the elevator once it has reached a control block). The distance an elevator can move is still tied to control blocks as currently (where an elevator will stop once it is two blocks below a control block)

As an illustration, I am trying to recreate Zelda 2 in minecraft and would like controllable elevators like shown 8 seconds into this video: https://youtu.be/88Uo_VNDhck

Thank you for reading, hope this is possible! (aka not a pain to code)

**Comment by Thutmose** [comment]
I can look into this, I have some code already in for riding this sort of thing, it is used for the crafts, the only adjustment here would be to make the player stay standing instead of using the sit animation

**Comment by Thutmose** [comment]
If you still want this, please re-make this issue in https://github.com/Thuts-Mods/ThutTech/issues
