### ISSUE TITLE
[1.10.2] Initializing crash

### ISSUE THREAD

**Issue by medsal15** [Thutmose/Thut#17]
Crash happens when I launch Minecraft. I use forge 2095 (for 1.10.2).
---- Minecraft Crash Report ----

WARNING: coremods are present:
  LoadingPlugin (Quark-r1.0-56.jar)
  LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  CCCDeobfPlugin (unknown)
  CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)
  CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
Contact their authors BEFORE contacting forge

// Oops.

Time: 08.10.16 07:25
Description: There was a severe problem during mod loading that has caused the game to fail

net.minecraftforge.fml.common.LoaderException: java.lang.NoClassDefFoundError: Could not initialize class thut.core.common.ThutCore
    at net.minecraftforge.fml.common.LoadController.transition(LoadController.java:186)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:576)
    at net.minecraftforge.fml.client.FMLClientHandler.beginMinecraftLoading(FMLClientHandler.java:218)
    at net.minecraft.client.Minecraft.func_71384_a(Minecraft.java:439)
    at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:351)
    at net.minecraft.client.main.Main.main(SourceFile:124)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
    at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
Caused by: java.lang.NoClassDefFoundError: Could not initialize class thut.core.common.ThutCore
    at java.lang.Class.forName0(Native Method)
    at java.lang.Class.forName(Class.java:344)
    at net.minecraftforge.fml.common.ProxyInjector.inject(ProxyInjector.java:50)
    at net.minecraftforge.fml.common.FMLModContainer.constructMod(FMLModContainer.java:575)
    at sun.reflect.GeneratedMethodAccessor4.invoke(Unknown Source)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.sendEventToModContainer(LoadController.java:239)
    at net.minecraftforge.fml.common.LoadController.propogateStateMessage(LoadController.java:217)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:483)
    at com.google.common.eventbus.EventSubscriber.handleEvent(EventSubscriber.java:74)
    at com.google.common.eventbus.SynchronizedEventSubscriber.handleEvent(SynchronizedEventSubscriber.java:47)
    at com.google.common.eventbus.EventBus.dispatch(EventBus.java:322)
    at com.google.common.eventbus.EventBus.dispatchQueuedEvents(EventBus.java:304)
    at com.google.common.eventbus.EventBus.post(EventBus.java:275)
    at net.minecraftforge.fml.common.LoadController.distributeStateMessage(LoadController.java:142)
    at net.minecraftforge.fml.common.Loader.loadMods(Loader.java:545)
    ... 10 more
## A detailed walkthrough of the error, its code path and all known details is as follows:

-- System Details --
Details:
    Minecraft Version: 1.10.2
    Operating System: Windows 10 (amd64) version 10.0
    Java Version: 1.8.0_25, Oracle Corporation
    Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
    Memory: 188339512 bytes (179 MB) / 395706368 bytes (377 MB) up to 2134114304 bytes (2035 MB)
    JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx2G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn128M
    IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
    FML: MCP 9.32 Powered by Forge 12.18.1.2095 89 mods loaded, 89 mods active
    States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
    UC  mcp{9.19} [Minecraft Coder Pack](minecraft.jar) 
    UC  FML{8.0.99.99} [Forge Mod Loader](forge-1.10.2-12.18.1.2095.jar) 
    UC  Forge{12.18.1.2095} [Minecraft Forge](forge-1.10.2-12.18.1.2095.jar) 
    UC  Aroma1997Core{${version}} [Aroma1997Core](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UC  CodeChickenCore{2.1.8.79} [CodeChicken Core](minecraft.jar) 
    UC  actuallyadditions{1.10.2-r65} [Actually Additions](ActuallyAdditions-1.10.2-r65.jar) 
    UC  alt{1.06} [Additional Loot Tables](AdditionalLootTables_1.10.2-1.06.jar) 
    UC  adobeblocks{6.0.4} [Adobe Blocks 2](AdobeBlocks-Forge-6.0.4.jar) 
    UC  advancedswords{1.3.0} [Advanced Swords](advancedswords-1.3.0-[1.9.4].jar) 
    UC  advancedaddons{1.1.0} [Advanced Addons](advancedaddons-1.1.0-[1.9.4].jar) 
    UC  adventurebags{0.4} [Adventure Bags](adventurebags-1.10.2-0.4.0.jar) 
    UC  Aroma1997CoreHelper{1.1.1.0} [Aroma1997Core|Helper](Aroma1997Core-1.9.4-1.1.1.0.jar) 
    UC  Aroma1997sDimension{1.0} [Aroma1997's Dimensional World](Aroma1997s-Dimensional-World-1.9.4-1.2.0.2.jar) 
    UC  Quark{r1.0-56} [Quark](Quark-r1.0-56.jar) 
    UC  AutoRegLib{1.0-2} [AutoRegLib](AutoRegLib-1.0-2.jar) 
    UC  basemetals{2.4.0} [Base Metals](BaseMetals_1.10.2-2.4.0.11.jar) 
    UC  Baubles{1.2.1.0} [Baubles](Baubles-1.9.4-1.2.1.0.jar) 
    UC  bookshelf{1.4.0.291} [Bookshelf](Bookshelf-1.10.2-1.4.0.291.jar) 
    UC  Bullseye{1.0.3} [Bullseye](Bullseye-1.9.4-1.0.3.jar) 
    UC  ceramics{1.10.2-1.1.1} [Ceramics](Ceramics-1.10.2-1.1.1.jar) 
    UC  mcmultipart{1.2.1} [MCMultiPart](MCMultiPart-1.2.1-universal.jar) 
    UC  CharsetLib{0.3.0-pre15} [â€½](Charset-0.3.0-pre15.jar) 
    UC  CharsetAudio{0.3.0-pre15} [â™«](Charset-0.3.0-pre15.jar) 
    UC  CharsetCarts{0.3.0-pre15} [U](Charset-0.3.0-pre15.jar) 
    UC  CharsetDecoration{0.3.0-pre15} [âš?](Charset-0.3.0-pre15.jar) 
    UC  CharsetDrama{0.3.0-pre15} [!](Charset-0.3.0-pre15.jar) 
    UC  CharsetFarming{0.3.0-pre15} [;](Charset-0.3.0-pre15.jar) 
    UC  CharsetGates{0.3.0-pre15} [&](Charset-0.3.0-pre15.jar) 
    UC  CharsetPipes{0.3.0-pre15} [|](Charset-0.3.0-pre15.jar) 
    UC  CharsetStorage{0.3.0-pre15} [#](Charset-0.3.0-pre15.jar) 
    UC  CharsetTweaks{0.3.0-pre15} [*](Charset-0.3.0-pre15.jar) 
    UC  CharsetWires{0.3.0-pre15} [+](Charset-0.3.0-pre15.jar) 
    UC  CharsetWrench{0.3.0-pre15} [/](Charset-0.3.0-pre15.jar) 
    UC  craftingcraft{4.1.6} [CraftingCraft](CraftingCraft_1.10.2-4.1.6.jar) 
    UC  craftingtweaks{6.1.12} [Crafting Tweaks](CraftingTweaks_1.10.2-6.1.12.jar) 
    UC  JEI{3.10.0.261} [Just Enough Items](jei_1.10.2-3.10.0.261.jar) 
    UC  cyclicmagic{1.7.10} [Cyclic](Cyclic-1.10.2-1.7.10.jar) 
    UC  cyclopscore{0.7.7} [Cyclops Core](CyclopsCore-1.9.4-0.7.7.jar) 
    UC  dailies{1.10.2-6} [Bailey's Dailies](dailies-1.10.2-6.jar) 
    UC  Waila{1.7.0} [Waila](Waila-1.7.0-B3_1.9.4.jar) 
    UC  darkutils{1.1.4.76} [Dark Utilities](DarkUtilities-1.10.2-1.1.4.85.jar) 
    UC  Ding{MC1.9.0v2} [Ding](Ding-1.10.2-1.0.0.jar) 
    UC  DungeonTactics{DT0.9.8} [DungeonTactics](DungeonTactics-1.10.2-0.9.8.jar) 
    UC  poweradvantage{2.3.0} [Power Advantage](PowerAdvantage_1.10.2-2.3.0.jar) 
    UC  electricadvantage{2.2.0} [Electric Advantage](ElectricAdvantage_1.10.2-2.2.0.jar) 
    UC  embers{0.004} [Embers](embers-0.004.jar) 
    UC  enchiridion{3.1.7} [Enchiridion](Enchiridion-1.9.4-3.1.7.jar) 
    UC  enderutilities{0.6.5-beta.2} [Ender Utilities](enderutilities-1.10.2-0.6.5-beta.2.jar) 
    UC  evilcraft{0.10.11} [EvilCraft](EvilCraft-1.10.2-0.10.11.jar) 
    UC  extraalchemy{0.3.0.2-release} [Extra Alchemy](extraalchemy-0.3.0.2-release.jar) 
    UC  ExtraUtils2{1.0} [ExtraUtils2](extrautils2-1.10.2-alpha-1.1.0a.jar) 
    UC  frt{6.4.4} [Fire's Random Things](FiresRandomThings-6.4.4.jar) 
    UC  fluxducts{1.0.4} [Flux Ducts](fluxducts-mc1.9.4-1.0.4.jar) 
    UC  substratum{1.8.1.0} [Substratum](Substratum-1.10.2-1.8.1.0.jar) 
    UC  foundry{2.2.0.1} [Foundry](Foundry-1.10.2-2.2.0.1.jar) 
    UC  ftfragileglass{1.8.1} [Fragile Glass and Thin Ice](Fragile Glass and Thin Ice 1.10.2-1.8.1.jar) 
    UC  fuelcanister{0.1} [Fuel Canister](Fuel Canister-1.0A mc 1.10.2.jar) 
    UC  harvestchevsky{b8} [Gentle Harvest](Gentle_Harvest_1.9_b8.jar) 
    UC  grimpack{3.4.16.45} [Grim Pack](Grim Pack-1.10.2-3.4.16.45.jar) 
    UC  ironchest{1.10.2-7.0.11.797} [Iron Chest](ironchest-1.10.2-7.0.11.797.jar) 
    UC  jeresources{0.5.1.56} [Just Enough Resources](JustEnoughResources-1.10.2-0.5.1.56.jar) 
    UC  levelup{${version}} [Level Up!](LevelUp!-0.12.2-1.10.2.jar) 
    UC  mantle{1.10.2-1.0.0.jenkins170} [Mantle](Mantle-1.10.2-1.0.0.jar) 
    UC  testdummy{1.11} [MmmMmmMmmMmm](MmmMmmMmmMmm-1.11.jar) 
    UC  moreanvils{6.0.2.11} [More Anvils](MoreAnvils-Forge-6.0.2.11.jar) 
    UC  nethercore{1.10.2-2.0.2} [Nether Core](nethercore-1.10.2-2.0.2.jar) 
    UC  fodc{1.9.1} [Ore Dictionary Converter](OreDictionaryConverter-1.9.1.jar) 
    UC  orespawn{1.1.0} [Ore Spawn](OreSpawn_1.10.2-1.1.0.jar) 
    UC  progressiveautomation{1.6.49} [Progressive Automation](ProgressiveAutomation-1.10.2-1.6.49.jar) 
    UC  railcraft{10.0.0-beta-2} [Railcraft](Railcraft_1.10.2-10.0.0-beta-2.jar) 
    UC  randomthings{3.7.6} [Random Things](RandomThings-MC1.10.2-3.7.6.jar) 
    UC  rfpr{8.0.0} [Real First-Person Render](Real First-Person Render-1.10.2-8.0.0.jar) 
    UC  refinedrelocation{@VERSION@} [Refined Relocation](RefinedRelocation-mc1.10.2-2.1.14.jar) 
    UC  AS_Ruins{16.2} [Ruins Spawning System](Ruins-1.10.2.jar) 
    UC  selimrandomstuff{3.2.0} [Selim's Random Stuff](SelimRandomStuff-1.10.2-3.2.0.jar) 
    UC  SilentLib{1.0.12} [Silent Lib](SilentLib-1.9.4-1.0.12-20.jar) 
    UC  steamadvantage{2.2.0} [Steam Advantage](SteamAdvantage_1.10.2-2.2.0.jar) 
    UC  tconstruct{1.10.2-2.5.3.jenkins387} [Tinkers' Construct](TConstruct-1.10.2-2.5.3.jar) 
    UE  thut_bling{1.0.0} [Thut's Bling](thut_bling-0.0.1.jar) 
    UE  thutcore{3.6.1} [ThutCore](thutcore-1.9.4-3.6.1.jar) 
    UE  thut_wearables{1.0.0} [Thut Wearables](thutcore-1.9.4-3.6.1.jar) 
    UE  thuttech{4.0.5} [Thut's Tech](thuttech-4.0.5.jar) 
    UC  underphangables{1.0.2} [Underp Hangables](underphangables-1.10.2-1.0.2.jar) 
    UC  underworld{0.1.11} [Underworld](underworld-1.10.2-0.1.11.jar) 
    UC  VTweaks{1.4.9.5} [V-Tweaks](VTweaks-1.10.x-1.4.9.5.jar) 
    UC  WailaHarvestability{1.1.9} [Waila Harvestability](WailaHarvestability-mc1.10.2-1.1.9.jar) 
    UC  waterstrainer{1.3.0} [Water Strainer](WaterStrainer-1.9.4-1.3.0.jar) 
    UC  icse{1.1.0.0} [I Can See Everything](Wawla-1.10.2-2.3.0.206.jar) 
    UC  wawla{2.3.0.202} [What Are We Looking At](Wawla-1.10.2-2.3.0.206.jar) 
    Loaded coremods (and transformers): 
LoadingPlugin (Quark-r1.0-56.jar)
  vazkii.quark.base.asm.ClassTransformer
LoadingPlugin (RandomThings-MC1.10.2-3.7.6.jar)
  lumien.randomthings.asm.ClassTransformer
CCCDeobfPlugin (unknown)

CoreMod (Aroma1997Core-1.9.4-1.1.1.0.jar)

CCLCorePlugin (CodeChickenLib-1.10.2-2.2.3.58-universal.jar)
  codechicken.lib.asm.ClassHeirachyManager
  codechicken.lib.asm.RenderHookTransformer
CodeChickenCorePlugin (CodeChickenCore-1.10.2-2.1.8.79-universal.jar)
  codechicken.core.asm.TweakTransformer
  codechicken.core.asm.DelegatedTransformer
  codechicken.core.asm.DefaultImplementationTransformer
    GL info: ' Vendor: 'Intel' Version: '4.0.0 - Build 10.18.10.4276' Renderer: 'Intel(R) HD Graphics'
    Pulsar/tconstruct loaded Pulses: 
        - TinkerCommons (Enabled/Forced)
        - TinkerWorld (Enabled/Not Forced)
        - TinkerTools (Enabled/Not Forced)
        - TinkerHarvestTools (Enabled/Forced)
        - TinkerMeleeWeapons (Enabled/Forced)
        - TinkerRangedWeapons (Enabled/Forced)
        - TinkerModifiers (Enabled/Forced)
        - TinkerSmeltery (Enabled/Not Forced)
        - TinkerGadgets (Enabled/Not Forced)
        - TinkerOredict (Enabled/Forced)
        - TinkerIntegration (Enabled/Forced)
        - TinkerFluids (Enabled/Forced)
        - TinkerMaterials (Enabled/Forced)
        - TinkerModelRegister (Enabled/Forced)
        - craftingtweaksIntegration (Enabled/Not Forced)
        - WailaIntegration (Enabled/Not Forced)

**Comment by Thutmose** [comment]
I will get fix for this pushed asap.

**Comment by Thutmose** [comment]
Thut Bling 0.0.2 has been uploaded, when it is approved, upgrading to it will fix this crash.
