### ISSUE TITLE
Can't make Call Controller

### ISSUE THREAD

**Issue by suntzu243** [Thutmose/Thut#171]
I can't get the call controller to work. Shift-right clicking with an unlinked device linker just shows two red dots that I can't seem to interact with and shows "Edit Mode: True." Am I doing something wrong?

**Comment by Thutmose** [comment]
try updating the the latest version for 1.15.2, it has more proper icons for that instead of the red dots, as well as fixes some interaction issues

**Comment by Thutmose** [comment]
If this issue still occurs for 1.15.2, please re-make in https://github.com/Thuts-Mods/ThutTech/issues
