### ISSUE TITLE
Thut Wearables GUI is shown above JEI / Inventory Tooltips

### ISSUE THREAD

**Issue by robaimes** [Thutmose/Thut#18]
As the title says, the TW GUI is displayes **above** tooltips, which cuts off text etc while the GUI is active. Examples shown below.

![JEI Tooltip](http://dl.aimes.eu/2016-10-08_08-36-01.png)

![Inventory Tooltip](http://dl.aimes.eu/2016-10-08_08-38-09.png)

**Comment by Thutmose** [comment]
this should be fixed in the version of ThutCore I released last night (3.6.2.1), I moved the gui to acting more like baubles' one, where it changes inventory to a different screen when pressed, mainly to fix this issue here, as well as issues with swapping items.
