### ISSUE TITLE
1.10.2 If I fall from just a few blocks high i will fall through a stationary elevator

### ISSUE THREAD

**Issue by LordHellscream** [Thutmose/Thut#20]
v 4.0.3
1. if a jump down on to a elevator from just 4-5 blocks high I instantly fall through, even tho the elevator is not moving.
2. sometimes I fall through when simply riding (not jumping or moving) an elevator downward and then get suffocated when the elevator crash down --- this doesnt happen everytime but it has happened 3-4 times in 2 days enough to be a major problem.

I have no noticed these issues in older versions (a couple months back)

**Comment by Thutmose** [comment]
See if this still occurs in 4.0.6.a?

**Comment by LordHellscream** [comment]
still see this in 4.0.6.a

also, when there is lag, the elevator sometimes get stuck in half way. also sometimes i get stuck in a "vibrating" state when I am getting on the elevator.

Also I really wanted to point out: I see NONE of the above issue with the old versions (when the elevator block were still placed instead of used, it was a couple months back). It seems the newer versions having a heck lot more issues.

**Comment by Thutmose** [comment]
It had a complete re-write when it was changed to support tile entities and other modded stuff, which is where these new bugs came from, I will try to get them fixed.

**Comment by Thutmose** [comment]
Can you make me a sample world, say a superflat with some elevators, that replicate these issues?  I have had a hard time getting any of these issues to occur for me, which makes it hard for me to fix.

**Comment by LordHellscream** [comment]
well, fall through thing i can definitely repro on a super flat world, to make it easier to repro, put on some kind of jetpack (mekanism/simply jetpack), but its not required.
The other issues are all happening sporadically, especially the stuck-half-way issue, its depends on the lag.

**Comment by Thutmose** [comment]
these are the elevators I have been testing with:

![image](https://cloud.githubusercontent.com/assets/2363472/19668549/92e4cf6a-9a26-11e6-978e-233ff4a22668.png)

none of them are able to replicate your issues, I have yet to fall through any of them.  This is being tested on a server running on the same machine I am playing on, so maybe it is a lag issue that I haven't been able to replicate yet?

**Comment by LordHellscream** [comment]
you can try this, make a 3x3 elevator (i've tried using polish granite or gold blocks, not sure if that matters), and then fly up (with a jetpack) to 10 -20 blocks higher , and try to fall on to the middle tile. every other time or so I fall through.
on my regular world, i was able to fall through much easier just by jumping down from the top floor onto the 2nd top floor , and i fall straight through to the bottom almost every time.
But on my test world i wasn't able to repro as easily (thus suggesting using the jetpack)

**Comment by Thutmose** [comment]
hmm, maybe I have not been testing from falling from high enough, for performance reasons I did reduce the distance above it that it checks, which may result in you falling through if you fall too quickly.

material shouldn't matter so long as they are normal solid blocks.

**Comment by Thutmose** [comment]
ahh yes, if you approach it too quickly, you do pass through, I will see about improving the detection of fast moving players for collision.

**Comment by Thutmose** [comment]
https://www.dropbox.com/s/fv2tysbn5cmexgc/thutcore-1.9.4-3.6.6.a.jar?dl=0

See if this version works any better? it might make you bounce a little when you first hit it.

**Comment by LordHellscream** [comment]
it helps, tried 30 times + only fell through once (normally happen almost everytime)

**Comment by Thutmose** [comment]
let me know if you can find a reliable way to still fall through, if you can, I can try to get it fixed as well, otherwise I will probably release what I have as a new version sometime tomorrow.

**Comment by LordHellscream** [comment]
make sense, this is definitely an improvement.

**Comment by Thutmose** [comment]
seems I forgot to close this a couple years ago
