### ISSUE TITLE
[Suggestion] Camouflage Controller Block

### ISSUE THREAD

**Issue by Kumomo** [Thutmose/Thut#25]
I don't think I saw a way to do this, but it would be amazing if we could camouflage the controller block. I've always been slightly annoyed with the back or sides of the block not matching the blocks around it, especially if it's sticking out on the exterior of a building.

This is my favorite Elevator Mod. Nice work!

**Comment by Thutmose** [comment]
Hmm, I should be able to get that done, I will look into it.

**Comment by Thutmose** [comment]
is this what you wanted?

![image](https://cloud.githubusercontent.com/assets/2363472/20291026/2a4de8ac-aaba-11e6-9098-cbd5939df75b.png)

**Comment by Kumomo** [comment]
YES <3 So much YES. :D I was not expecting such a fast response!

Edit: Thanks for the super fast upload. Some glass types come out a bit wonky, but otherwise it's just what I wanted. 
![thut controllers](https://cloud.githubusercontent.com/assets/6624938/20292489/fbf10a82-aabb-11e6-9e1b-dc00a02b1504.png)

**Comment by Thutmose** [comment]
ya, I wasn't expecting it to work well on transparent blocks, it also doesn't work well on grass iirc, I can look into trying to fix that at some point

**Comment by Kumomo** [comment]
I'm really happy with it regardless! This makes my day. ^_____^ And I love that the numbers aren't visible from the other sides unless I choose to. Thanks so much.
![2016-11-14_22 50 06](https://cloud.githubusercontent.com/assets/6624938/20292618/06a0fd92-aabd-11e6-8dce-90106fdfc1f5.png)
