### ISSUE TITLE
[1.11.x] [ThutTech-5.0.0.b] Lowercase controlPanel_1.png and controlPanel2.png

### ISSUE THREAD

**Issue by hennign** [Thutmose/Thut#28]
I'm not experienced with modding so if I'm wrong about anything, sorry.

**Mod:** ThutTech-5.0.0.b, ThutCore-4.0.1.h
**Bug:** Getting purple and black missing texture on sides after using device linker.

**Steps to reproduce:**
1. Place elevator control block.
2. Right click side with device linker.

**Solution:**
I believe this issue is because 1.11 automatically lowercases asset names when trying to load them. I got the following error message in my latest.log file.

> [Client thread/WARN]: Failed to load texture: thuttech:textures/blocks/controlpanel_1.png
> java.io.FileNotFoundException: thuttech:textures/blocks/controlpanel_1.png

I unzipped the thuttech jar, changed the two files to lower case, rezipped and then the textures loaded normally when I re-tested.

The two files are:
 https://github.com/Thutmose/Thut/blob/1.11.x/ThutTech/src/main/resources/assets/thuttech/textures/blocks/controlPanel_1.png
and
https://github.com/Thutmose/Thut/blob/1.11.x/ThutTech/src/main/resources/assets/thuttech/textures/blocks/controlPanel_2.png

**Comment by Thutmose** [comment]
ahh right, I had forgotten to lowercase those, I went and did all 3000 assets in pokecube, and forgot about the ones in ThutTech lol.

I will try to get to that tomorrow, thanks for the report.

**Comment by Thutmose** [comment]
This should be fixed in 5.0.0.c, which I just uploaded to curseforge.
