### ISSUE TITLE
Game crashed while walking onto an elevator

### ISSUE THREAD

**Issue by snurre0** [Thutmose/Thut#29]
Hi,

Was playing around with the elevator mod for a few hours in creative, in a new single player world I created.
I made a bunch of elevators, including a tall elevator shaft with an elevator of 5x5x5 in it. Tested it many times and it worked fine.

Then, I switched to survival to get a zoombie to follow me into the elevator, and just as I entered the elevator floor, my game crashed.
Now I can't open my single player world at all (without removing the mod I guess), it just crashes.

Crashreport: http://pastebin.com/pX2ZVgEp

MC: 1.11
Forge: 13.19.0.2157
Thut's Elevators: 5.0.0.d
ThutCore: 4.0.1

Best regards,
Morten

**Comment by Dushess** [comment]
One more solution, open map in MCEdit and remove tile-entities of affected elevator.
But yes, it's still a bug...

**Comment by snurre0** [comment]
It's really just a test world for this mod only, so I can just delete it.
Thanks for the tip though :)

**Comment by Thutmose** [comment]
try this with the following version of ThutCore: https://www.dropbox.com/s/vdn54fvzse69tz5/thutcore-4.0.1.k.jar?dl=0

seems my earlier version may have had issues with the access transformer it uses.

**Comment by snurre0** [comment]
Wow, that was fast! :) 
I will try the new core when I have time, maybe in a few days. Thank you!

**Comment by snurre0** [comment]
Now it works again, thank you! :)
