### ISSUE TITLE
Forge 1.7.10 (1448+) Missing Fluid Registry

### ISSUE THREAD

**Issue by egeis** [Thutmose/Thut#3]
Receiving the following error on world creation.

"The fluid registry is corrupted. A fluid net.minecraftforge.fluids.Fluid blockdust is not properly registered. The mod that registered this is broken."

**Comment by Gentleman-Ghost** [comment]
I'm getting the same error in my modpack but I can't figure out which mod is causing it.

**Comment by egeis** [comment]
The issue is a result of updating Forge, im not exactly sure which version does it but 1448 is not compatabile anymore.

**Comment by Thutmose** [comment]
I think this was fixed in later releases, so closing for now, re-open if it still exists.
