### ISSUE TITLE
Elevators and Glowstone

### ISSUE THREAD

**Issue by brisingraerowing** [Thutmose/Thut#33]
Would it be possible to allow glowstone in elevators to emit light? I would like to use glowstone to light up my elevator, but it doesn't emit light after forming the elevator.

If not, what possible light sources can be used?

I am in 1.10.2 BTW, as most mods I use aren't updated yet.

**Comment by Squirtle8459** [comment]
although this doesn't fix the issue, I'd suggest placing Glowstone in the 'painter' block added by EnderIO and placing the block you are using to build the walls of the elevator in there as well. it will camouflage the block so its a different texture of glowstone..

**Comment by Thutmose** [comment]
ya, that will probably be best idea, the elevator cannot emit light, as it is not a block, the only way for it to emit light would be to place a whole bunch of glowing air blocks along its path.

**Comment by Thutmose** [comment]
closing issues for unsupported versions
