### ISSUE TITLE
Pokecube Alternative v 18 1.10.2

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Thut#35]
P3rf3ct_Zer0 - Yesterday at 8:23 PM
You can switch moves though.
0.18 is the version.
Thutmose - Yesterday at 8:24 PM
try recalling then switching?
P3rf3ct_Zer0 - Yesterday at 8:24 PM
Yeah then the pokecubes juggle
they don't actually change slots.
Thutmose - Yesterday at 8:25 PM
odd and ctrl or alt, or wahtever the default is doesn't work?
P3rf3ct_Zer0 - Yesterday at 8:26 PM
To reproduce send out a pokecube fight and catch another that is not yet on your hotbar; then call back a pokecube to bar one; now hold the newly caught pokecube and and first send out your pokecube; then while your starter is out right click to send the new pokecube to your belt. Now when you click R to send out a pokecube it juggles the cubes and you can not send out or add any to hotbar. Its like ID slot 1 freezes. Also you cannot force the bar to change. To fix go to a healer and manually drag your pokecubes to the correct slots or place all pokecubes in the pc.(edited)
Thutmose - Yesterday at 8:28 PM
[10:25 PM] Thutmose: odd and ctrl or alt, or wahtever the default is doesn't work?
P3rf3ct_Zer0 - Yesterday at 8:28 PM
Nope; I wasn't ignoring you btw XD(edited)
Thutmose - Yesterday at 8:28 PM
what happens when you use them?
P3rf3ct_Zer0 - Yesterday at 8:28 PM
they work as intended just get unorgnized thats all and locks to slot one.
IE you cannot change slots XD
So if you have 3 pokemon you can only use the 2 also you can manage to juggle 7 pokemon using this glitch.

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions
