### ISSUE TITLE
[1.11] [thuttech-5.0.0] [Forge 2199] Duped Floors upon logging in

### ISSUE THREAD

**Issue by shortybsd** [Thutmose/Thut#36]
When everyone leaves server and people reconnect the only elevator I have dupes. It has only 5 floors but every single block between all the floors have the floor itself duped all the way up to block 256 in height. When clearing out all the floors, the top floor sitting on block 256 is the active one, as it will come back down after anything underneath it is cleared.
https://imgur.com/a/DtXzo

**Comment by Thutmose** [comment]
odd, that sounds like for some reason, it is being sent to y=256. and being "killed" the entire way up, is there any error in server console when this happens?  The elevators I have tested on servers have not done this.

**Comment by shortybsd** [comment]
Was very odd brother, I will clear all the logs and restart the server to see if anything out of the ordinary comes forward or will see if it does it again.

**Comment by shortybsd** [comment]
Ok I restarted server and my elevator is back from the 2nd floor up all the way to block 256. Nothing in any of my log files for Thuttech for any errors.

**Comment by Thutmose** [comment]
hmm very odd indeed, I will try to look into this whenever I get time.

**Comment by shortybsd** [comment]
Thank you very much, been dying to put your mod back in my pack as it is by far the best realistic elevator mod out.

**Comment by Thutmose** [comment]
should be fixed now.
