### ISSUE TITLE
[SMP 1.10.2] Elevator stops working (Forge 1.10.2 - 12.18.3.2221 & thuttech-4.0.10.b.jar)

### ISSUE THREAD

**Issue by PorkchopFu** [Thutmose/Thut#38]
I'm experiencing a debilitating, reoccurring issue where the elevator stops working after logging out out. The blocks comprising the elevator return to their original colors, but right clicking the elevator floor area with the device linker prints the message "Elevator owned by <user>" as if the elevator is still active. Shift + right clicking the elevator floor area with a stick reports that the elevator was killed, but after recreating the elevator by specifying the size (4x4) with the device linker, floors cannot be set on the control blocks and attempting to do so by shift + right clicking with the device linker report "reset device linker".

At this point I have not found a repeatable way to get the elevator working again, even after destroying all the control blocks and generating a new device linker. I would also like to add that all elevator blocks and device linkers were generated using JEI's cheat mode while in gamemode 1. 

I am using Minecraft Forge 1.10.2 - 12.18.3.2221 and thuttech-4.0.10.b.jar. Please let me know what I can do to help test. This is far and wide the best elevator available and would love to see it working consistently. Thanks.

**Comment by PorkchopFu** [comment]
I figured out that I wasn't shift + right clicking the elevator after creation before setting the floor, which allows floors to be reset. However, the problem of the elevator breaking after every logout persists when using both thuttech-4.0.10.b.jar and thuttech-4.0.10.jar for Minecraft 1.10.2.

**Comment by Dushess** [comment]
Only one way to recreate it in this case: remove all elevator related tile-entities in MCEdit, but problem source will not be fixed.

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions
