### ISSUE TITLE
Problem with rendering (Thutcore)

### ISSUE THREAD

**Issue by solarregis** [Thutmose/Thut#4]
From what I can tell, this mod uses a custom renderer that doesn't play nicely with anything not around you on world load (Thaumcraft models appear "exploded", Intangible's Soul Relays appears as straight lines, mob models can simply not render, making them invisible, etc.), thus making the game almost unplayable.
Ordinarily, this wouldn't be an issue and I would just remove the mod causing the problem, but Thutcore adds a persistent registry type (thutcore:biometypes), meaning that a world that has previously been loaded with Thutcore, then can't be loaded without it.

**Comment by Thutmose** [comment]
Hmm, I have not noticed any issues with thaumcraft models (I use thaumcraft for testing mod compatibilty stuff), can you attach a screenshot, as well as instructions as how to replicate (preferably including a few mods as possible)

If it is the custom renderer, I can see about fixing/removing it, as I don't think I include any blocks yet that actually use it.

**Comment by Thutmose** [comment]
See if the latest release of ThutCore (http://minecraft.curseforge.com/projects/thutcore/files 2.3.2) has the same issue, it no longer attempts to register a model type.

I will see if I can find out how to tell forge to let the world load without the registry, a registry is needed incase addon mods add extra biome types.

**Comment by Thutmose** [comment]
Temporary solution to the persistant registry problem:

Get something like NBTExplorer.

Find your world folder, and fine the level.dat

Open level.dat with NBTExplorer

Open down to the thutcore:biometypes entry, as seen here:
![image](https://cloud.githubusercontent.com/assets/2363472/13544133/1b041c66-e249-11e5-8d99-c544c56c75b4.png)

Select that tag, and then click Delete Tag, as seen here:
![image](https://cloud.githubusercontent.com/assets/2363472/13544139/38d9ae2c-e249-11e5-9749-6bfd2e29b527.png)

Then click Save All Modified Tags, as seen here:
![image](https://cloud.githubusercontent.com/assets/2363472/13544159/5dda1540-e249-11e5-88df-878e5f6a18a8.png)

That will allow the game to load after ThutCore has been removed.

**Comment by solarregis** [comment]
Cheers Thut. Wasn't able to recreate the render issue in my survival world or a test world, annoyingly enough

**Comment by Thutmose** [comment]
No problem, I couldn't get the render issue to replicate on my end either, but since that renderer wasn't used, I removed it anyway.

Other than editing the level.dat though, there doesn't seem to be a way to fix the registry issue, as the check for that seems to be hardcoded into forge.

**Comment by Thutmose** [comment]
closing this as the world issues have been fixed in recent versions of forge.
