### ISSUE TITLE
Need to have a larger elevator space

### ISSUE THREAD

**Issue by brutonandrew573** [Thutmose/Thut#41]
I am using this in a theatre world and need the curtain and the borders to be on the elevator, but they are too large for the elevator, is there a config file I can open to change this? (I am using MC version 1.10.2 Forge)

**Comment by Thutmose** [comment]
thuttech.cfg in config:

    # Max allowed height of a lift.
    I:maxHeight=5

    # Max allowed radius of a lift (2 gives 5x5 as maximum).
    I:maxRadius=2
