### ISSUE TITLE
Thut Essentials - Nick command issue

### ISSUE THREAD

**Issue by Gunner76th** [Thutmose/Thut#43]
We are having a slight problem with the /nick command. We are able to change nicknames just fine, however if we try to change names back to their normal MC name (to include capitalization) the name displayed in MC ends up just being blank. Example: I can do /nick Gunner and when I chat is shows up as <Admin Gunner> (we are using prefixes from Thut Perms also for our permission groups), however if I try to set my name back to /nick Gunner76th then what shows up in chat is <Admin   >. It is as if I changed my name to a blank space. I looked through my player's data file to see if it was a tag added there that I could remove, as well as in the configs, and I can't see how or where you store the name change information. 

So my issue is two fold:

1) How do you properly reset a player's username so that it shows their actual MC name? 
2) Where are the name changes stored on the server, so that if needed server admins can manually edit those changes?

**Comment by Gunner76th** [comment]
Also we are running forge 2215 and Thut Essentials 1.5.25 with Thut Permissions 0.4.0

**Comment by Thutmose** [comment]
iirc blank /nick now does this? re-make this issue on https://github.com/Thutmose/ThutEssentials/issues if it is still around
