### ISSUE TITLE
[Bug][1.10.2] energyUse config has no effect.

### ISSUE THREAD

**Issue by grundyboy34** [Thutmose/Thut#44]
I'm currently making a modpack and would prefer to require the elevator to use power. Power transfer is happening via Immersive Engineering, so it should support Forge Energy just as well, however the config to enable power use seems to have no effect. The Elevators still operate even when nothing is connected, and don't drain energy when connected.

**Comment by Thutmose** [comment]
this was fixed for the 1.12.2 version, will be out in next version released for it.
