### ISSUE TITLE
Update to remove the debug console line

### ISSUE THREAD

**Issue by AstroxV** [Thutmose/Thut#45]
Can you please release an update (or beta) so the test-debug line won't spam the logs and console of the server? It makes it impossible to see what else is going on in the console and makes log files unnecessarily long.
It started happening the last update which was 31/01 and since then it has been changed in the code, but never pushed through to a release.
I'm talking about the line: 
[13:42:01] [Netty Server IO - Mob AI Thread-0/INFO] [STDOUT]: [thut.api.pathing.ThutPathFinder:isEmpty:533]: test

which happens pretty much whenever a mob moves.

It would really be appreciated if you can push through the fix for this.

**Comment by Thutmose** [comment]
Sry about this, I got rather ill after I removed that, and didn't get around to compiling and uploading the fix, I will get it dealt with ASAP, I removed that debug print here in the code:

https://github.com/Thutmose/Thut/commit/e1a76af9aa0b6c7c970d0f9b023404116f99c8f9

But then didn't get it compiled and uploaded.
