### ISSUE TITLE
Elevator is always trying to go north and west.

### ISSUE THREAD

**Issue by DeadPigman17** [Thutmose/Thut#49]
For example, if I break an elevator's north wall it'll will instantly go north. And this makes you unable to have elevators with an entrance from north or west.
![2017-04-10_03 19 06](https://cloud.githubusercontent.com/assets/22800252/24842816/c87ba258-1d9c-11e7-9733-bc2950d2b466.png)

EDIT: Sometimes it goes east, it's really weird...
EDIT 2: I'm using the last 1.11 version of the mod.

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions
