### ISSUE TITLE
Crash with forge 1.9-12.16.0.1859-1.9

### ISSUE THREAD

**Issue by Enohpoxas** [Thutmose/Thut#5]
[Here is the Pastebin link to the crash report](http://pastebin.com/SrRa7eKa). The latest version of Forge as well as all previous versions produce this crash with Thutcore 3.0.3. I wish I could give you more info, but this is really all I have to show. I've tried all versions of Forge for 1.9 with Thutcore 3.0.3. I'm not sure how else to troubleshoot it.

**Comment by Thutmose** [comment]
Forge for 1.9 has been changing lots and lots of things since it came out, so is liable to crash for random reasons.  I will see about re-compiling for the latest version probably tomorrow or so.

I think 3.0.3 was compiled against forge 1813.

**Comment by Enohpoxas** [comment]
Thanks for the quick response! I've really been looking forward to trying out PokeCube for 1.9 so thanks for doing this.

**Comment by Thutmose** [comment]
no problem, tomorrow or so I will probably get around to compiling ThutCore as well as the pokecube mods for the latest 1.9.

**Comment by Thutmose** [comment]
Uploaded new versions, note that there seems to be a rather major bug in forge/vanilla that causes crashes randomly on fluid flow and fire ticking.
