### ISSUE TITLE
Elevator Issues with Forge Server restart and Sponge issues.

### ISSUE THREAD

**Issue by DrakeEldridge** [Thutmose/Thut#50]
Forge version: forge-1.10.2-12.18.3.2272-universal
thutcore-3.12.2
thuttech-4.0.10.b

Whenever I restart my server the 2x2 elevator moves out of place. Sometimes it is just a tiny bit out of place and when u hit the buttons it pops back into place. But most of the time it is completely stuck in the wall and wont pop back into place. Because of this it needs to be remade after every restart.

From the screenshots you can see that when it gets stuck in the wall, i can break the blocks around it and it will go up and down, but will still be out of place and need to be remade to get it back in its proper spot.
[ElevatorIssues.zip](https://github.com/Thutmose/Thut/files/961078/ElevatorIssues.zip)

I also posted this issue on the sponge github. It seems your mod and sponge do not work correctly. I can make elevators, but they are broken and will not go up and down properly and get stuck. So if I am on second floor and press button to go to floor 1, it gets stuck. But if I relog the elevator is on floor one. So I am not sure why it does that. 
Also if I copy a single player map and put it on my forge server with sponge, it deletes all the elevators and ships from your mod and Valkyrien Warfare. Without sponge everything works fine except for the issue stated at the top of this post.
Link to Sponge Issue Post:
https://github.com/SpongePowered/SpongeForge/issues/1465

**Comment by Thutmose** [comment]
On the spongeforge issues, see if disabling the optimizations it does for mobs fixes things, the elevators are technically mobs, and spongeforge does a whole bunch of stuff that stops them working

I will see if I can find out what is going wrong on the server with the elevator, it shouldn't move like that... do you know if there is anything that it might be pushing off?

**Comment by DrakeEldridge** [comment]
i have no idea whats moving the elevators. I will look at the sponge config and see what changes I can make that might fix it.

**Comment by DrakeEldridge** [comment]
Ok I have tried changing a bunch of sponge settings but I cant seem to find anything that stops sponge from deleting the elevators (along with ships from Valkyrien Warfare.)

**Comment by Thutmose** [comment]
cleaning up old issues for unsupported versions
