### ISSUE TITLE
Elevator creating a tower of blocks.

### ISSUE THREAD

**Issue by GeorgeZn** [Thutmose/Thut#51]
So, the thing is that I'm playing with random things's spectre dimension, and I tried making an elevator, it worked, but every time I come out of the spectre dimension and get back in, it creates a tower of blocks from whatever height the elevator was when I got out, to an arbitrary height, breaking through the spectre blocks (supposedly unbreakable), with the elevator entity sitting at top. I'm currently using minecraft 1.10.2 with version 4.0.10.c of the mod, and randomthings version MC1.10.2-3.7.7 alongside other mods. Also I'm including this screenshot with the f3 menu open, what I'm looking at is the elevator entity at the height it was in the tower, and only comes down after I call it to one of the "floors"
![2017-05-25_16 12 00](https://cloud.githubusercontent.com/assets/24234677/26471180/586726c0-4166-11e7-8755-c9bdb1952aba.png)

**Comment by Thutmose** [comment]
this should now be fixed.
