### ISSUE TITLE
Crashing when trying to load the mod

### ISSUE THREAD

**Issue by DimitarBogdanov** [Thutmose/Thut#52]
When I try to load the mod, no matter alone or with other mods I get this:
`The game crashed whilst there was a severe problem during mod loading that has caused the game to fail`
[Full crash report can be found here!](https://pastebin.com/UfamcU9g)
It happens on both ThutMods-2.0 and 2.1... Help plz 😄  
I am sorry for the old version but I needed it for 1.7.10.

**Comment by DimitarBogdanov** [comment]
BTW just tested it happens on all the versions I even upgrated to 1.8.9! (My mods came out)

**Comment by oskarkaczmarek** [comment]
yea i got crash like this:
```
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
The game crashed whilst there was a severe problem during mod loading that has caused the game to fail
Error: cpw.mods.fml.common.LoaderException: java.lang.NoClassDefFoundError: thut/tech/common/blocks/lift/TileEntityLiftAccess
```
Server runs smoothly, but client cannot start. MC 1.7.10 Infinity evolved 3.0.2 modpack.

**Comment by Thutmose** [comment]
closing issues for unsupported versions
