### ISSUE TITLE
pokecube or thutcore updated mods crashing game at start and load only when these mods are present

### ISSUE THREAD

**Issue by rydgemittlestadt** [Thutmose/Thut#54]
forge versions 2387-2400

---- Minecraft Crash Report ----
// But it works on my machine.

Time: 7/8/17 12:31 AM
Description: Rendering screen

java.lang.NullPointerException: Rendering screen
	at pokecube.core.client.gui.GuiChooseFirstPokemob.func_73863_a(GuiChooseFirstPokemob.java:178)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)
	at net.minecraft.client.renderer.EntityRenderer.func_181560_a(EntityRenderer.java:1115)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1117)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:397)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at pokecube.core.client.gui.GuiChooseFirstPokemob.func_73863_a(GuiChooseFirstPokemob.java:178)
	at net.minecraftforge.client.ForgeHooksClient.drawScreen(ForgeHooksClient.java:349)

-- Screen render details --
Details:
	Screen name: pokecube.core.client.gui.GuiChooseFirstPokemob
	Mouse location: Scaled: (213, 119). Absolute: (427, 240)
	Screen size: Scaled: (427, 240). Absolute: (854, 480). Scale factor of 2

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['RydgeMittlestadt'/2230, l='MpServer', x=-154.50, y=72.00, z=242.50]]
	Chunk stats: MultiplayerChunkCache: 82, 82
	Level seed: 0
	Level generator: ID 00 - default, ver 1. Features enabled: false
	Level generator options: 
	Level spawn location: World: (-156,64,244), Chunk: (at 4,4,4 in -10,15; contains blocks -160,0,240 to -145,255,255), Region: (-1,0; contains chunks -32,0 to -1,31, blocks -512,0,0 to -1,255,511)
	Level time: 97 game time, 97 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: survival (ID 0). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['RydgeMittlestadt'/2230, l='MpServer', x=-154.50, y=72.00, z=242.50]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:415)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2732)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:418)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:483)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)

-- System Details --
Details:
	Minecraft Version: 1.12
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_25, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 403919976 bytes (385 MB) / 1046835200 bytes (998 MB) up to 6388776960 bytes (6092 MB)
	JVM Flags: 6 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xmx6G -XX:+UseConcMarkSweepGC -XX:+CMSIncrementalMode -XX:-UseAdaptiveSizePolicy -Xmn512M
	IntCache: cache: 0, tcache: 0, allocated: 13, tallocated: 95
	FML: MCP 9.40 Powered by Forge 14.21.1.2387 13 mods loaded, 13 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored
	UCHIJAAAA	minecraft{1.12} [Minecraft] (minecraft.jar) 
	UCHIJAAAA	mcp{9.19} [Minecraft Coder Pack] (minecraft.jar) 
	UCHIJAAAA	FML{8.0.99.99} [Forge Mod Loader] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	forge{14.21.1.2387} [Minecraft Forge] (forge-1.12-14.21.1.2387.jar) 
	UCHIJAAAA	thutcore{5.1.0} [ThutCore] (thutcore-5.1.0.jar) 
	UCHIJAAAA	pceditmod{1.10.2-2.0.0} [In-game NBTEdit - Pokecube Edition] (Pokecube Core-6.0.13.jar) 
	UCHIJAAAA	pokecube{6.0.13} [Pokécube Core] (Pokecube Core-6.0.13.jar) 
	UCHIJAAAA	pokecube_ml{0.1.0} [Pokecube Model Loader] (Pokecube Core-6.0.13.jar) 
	UCHIJAAAA	pokecube_mobs{2.5.0} [Pokécube Mobs] (Pokecube Mobs-2.5.0.jar) 
	UCHIJAAAA	pokecube_origin{@VERSION@} [Pokecube Origin] (Pokecube Mobs-2.5.0.jar) 
	UCHIJAAAA	pokecube_adventures{6.0.5} [Pokécube Revival] (Pokecube Revival-6.0.5.jar) 
	UCHIJAAAA	pokecube_compat{1.0} [Pokecube Compat] (Pokecube Revival-6.0.5.jar) 
	UCHIJAAAA	pokeplayer{@VERSION} [Pokecube Mystery Dungeon] (Pokecube Revival-6.0.5.jar) 
	Loaded coremods (and transformers): 
	GL info: ' Vendor: 'NVIDIA Corporation' Version: '4.5.0 NVIDIA 382.33' Renderer: 'GeForce GTX 970/PCIe/SSE2'
	Launched Version: 1.12-forge1.12-14.21.1.2387
	LWJGL: 2.9.4
	OpenGL: GeForce GTX 970/PCIe/SSE2 GL version 4.5.0 NVIDIA 382.33, NVIDIA Corporation
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x Intel(R) Core(TM) i7-4820K CPU @ 3.70GHz

**Comment by Thutmose** [comment]
Did you change any configs? that error indicates that it somehow started without loading any pokemobs at all, which shouldn't be possible with the normal configs, it means something interfered.

Using that exact set of mods:
![image](https://user-images.githubusercontent.com/2363472/27983635-941551b0-638f-11e7-95a5-dcbcbfb2952b.png)
it works fine on my end, so it is probably something wrong on the config side, try deleting all the configs and letting them regenerate?

**Comment by rydgemittlestadt** [comment]
It was just the 6.13 poke core 6.14 fixed the problem on my end

**Comment by Thutmose** [comment]
closing this issue then, idk why it was crashing before, but glad it seems to be fixed.
