### ISSUE TITLE
v1.12 - no floor building possible

### ISSUE THREAD

**Issue by AntonTrapp** [Thutmose/Thut#55]
1.12 with forge 1.12-14.21.1.2404 is NOT working.

 

The floor can not be set if there is an elevator block in the middle. If you do not set an elevator block you can build the floor but no elevator :D

**Comment by Thutmose** [comment]
it works fine as far as I can tell, please edit this issue with better description, or make a new one with a better description of your issue.

![image](https://user-images.githubusercontent.com/2363472/27996234-e9a57c78-64ab-11e7-9067-20b1d5b00967.png)

**Comment by AntonTrapp** [comment]
Thank you for your fast reply. The video just looks awesome... really need this mod :)

The problem is:

When the elevator block is in the middle of the platform the shift-leftclick to make a platform does not work (does nothing at all). The red rectangle shows the whole platform, shift + leftclick -> nothing. (right one)

I can only create platforms that do not contain the elevator block (same material on the whole platform). Shift + leftclick -> "Successfully Made Elevator" (left one) - but without the elevator block the rest of the tutorial does not work.

![2017-07-09_19 46 50 kopie](https://user-images.githubusercontent.com/168248/27996308-a816710c-64df-11e7-839e-d4a886c510f4.png)

**Comment by Thutmose** [comment]
Ahh, ok, so the creation step of the video is outdated, now you just use the device linker, as mentioned in the book (if the book wasn't bugged for you)

The elevator block is no longer needed as part of the structure, instead it is pulled from inventory and consumed when you make the elevator (only in survival mode)

You make the elevator with just the device linker, you right click one corner, then shift right click the next corner, and everything in between is made into an elevator

**Comment by AntonTrapp** [comment]
That's why I always (try to) read the readme files (or books in this case) :D

Seems like all the tutorials I found (3 text + 2 videos) are outdated. Mod is working the way you described it. TNX!

Do you have a paypal account for donations? As I am playing minecraft with my nephew and niece and this part does save me time I can work more and so it is saving me money ;)

**Comment by Thutmose** [comment]
No problem, I don't know why the book wouldn't have been working, unless, are you using a different language from en_US? the book format got changed in 1.12, which broke some old books (not all of them) and it could have broken it if another language was being used.

there should be a "donate" button on the curseforge page, it says to "Pokecube" as that was the first mod I setup the button for, and just used the same one for all my mods.

**Comment by AntonTrapp** [comment]
Yes, I do use a different locale :) - and I found the donate button. tnx
