### ISSUE TITLE
v1.12 - book not very helpful

### ISSUE THREAD

**Issue by AntonTrapp** [Thutmose/Thut#56]
The book with the content "Invalid book tag" is not very helpful ;)

**Comment by Thutmose** [comment]
are you using a recent version? mine seems to work fine:

![image](https://user-images.githubusercontent.com/2363472/27996206-4f1596b6-64ab-11e7-8ab1-19df37595e10.png)

**Comment by AntonTrapp** [comment]
Yes, the latest version together with forge: 1.12-14.21.1.2404:

![bildschirmfoto 2017-07-09 um 19 39 48](https://user-images.githubusercontent.com/168248/27996260-7f7feb2a-64de-11e7-9d12-52873b6d1569.png)

**Comment by Thutmose** [comment]
Which version specifically?

**Comment by AntonTrapp** [comment]
Mods show: TutCore 5.0.0 and Thut's Tech 6.0.0. Will try to run them without any other mods today. Maybe there is a conflict somewhere...

Just tried to run it (only with forge and the 2 thut's files in the mods). Same problem.

**Comment by Thutmose** [comment]
Which locale are you using? I could see if It is a problem with that, I didn't want to try to do blanket find/replace in the other lang files to fix issues, as some languages use characters that I might mess up, but I guess I could try it anyway.

**Comment by AntonTrapp** [comment]
Deutsch (Deutschland) -> German, but the same happens with English (US), so I do not think that the locale is the problem.

**Comment by Thutmose** [comment]
Oh, Isn't latest thuttech 6.0.1? try updating to that and see if it fixes the english book, I can probably try to find/replace the fix in the german book as well and see about updating (I think I also have a chinese book I should probably fix too)

**Comment by AntonTrapp** [comment]
Working! Somehow I downloaded 2 x 1.12.jar files as "newest".

Thank you very much for your help!

**Comment by Thutmose** [comment]
Ahh ok, also seems I don't have a de_DE translation for the book, only en_US and zh_CN, so it should give the en_US one even if it is set to German

**Comment by AntonTrapp** [comment]
I can translate the book to german if you want. It's not a bulky volume :)

**Comment by Thutmose** [comment]
that would be wonderful, the original text can be found here: https://github.com/Thutmose/Thut/blob/1.9/ThutTech/src/main/resources/assets/thuttech/lang/en_US.lang

But I made the book with this:
http://minecraft.tools/en/book.php

It might be easier to make it with that.

where after clicking "generate command" I just paste the "{pages:...}" into the lang file

You can either submit a PR to edit the existing de_DE, or just paste the command generated by that page, and I can edit the .lang myself.

**Comment by AntonTrapp** [comment]
What's the "call controller" (shift-right click on the top of a elevator controller)? Need to know this for a proper translation...

And tile.railgun.name

**Comment by Thutmose** [comment]
tile.railgun.name was a testing thing for some performance related code, idk if it will ever actually get put in properly, it was a block that fired blocks, and resulted in explosions based on how strong the fired blocks was.

"call controller" is a button which only displays the button for that controller's floor, do you press it and the elevator comes to you, ie is "called" to your location.  Effectively all it does is disable all the other buttons, and move the curren't floors button to the middle of the screen.
