### ISSUE TITLE
RF API conflict

### ISSUE THREAD

**Issue by pujxstick** [Thutmose/Thut#59]
I installed this mod within my FTB Infinity Evolved pack and got a crash like this on startup 
I am using 1.7.10

**The RF API that is being used (1.7.10R1.0.2 from <unknown>) differes from that that is reported as being loaded (1.7.10R1.0.13 from ImmersiveEngineering-0.7.7.jar)**

<unknown> I believe is the mod. I removed the mod and started up again and no crash or error.
Not sure if I can replace the API within the mod with the newer one? Please help

**Comment by Thutmose** [comment]
it might work to delete the rf package from the jar, try that, 1.7.10 support ended 2 years ago so Icant help much more than this suggestion.

open the jar with 7zip or something, then delete the rf api, i dont remember exactly how it is packaged, havent lookedat the 1.7.10 version for nearly 2 years
