### ISSUE TITLE
[Question] about elevator and custom tile-entities compatibility.

### ISSUE THREAD

**Issue by Dushess** [Thutmose/Thut#60]
How elevator handles for example chiseled blocks from C&B inside? It can move with elevator or will stay on positions, when elevator goes up/down? I asking, because want use chiseled blocks as walls for elevators. Now we have 2 mods of this theme: Chisels&Bits, and LittleTiles, both uses segmented block as tile-entity.

**Comment by Thutmose** [comment]
it might work, not sure, it depends on what they do with their rendering.  I have confirmed that it works with a variety of vanilla tile entities, as well as some custom ones added by my mods, but I cannot confirm if it will work with any random tile entity renderer, they might do strange things that I don't account for.  Test it and let me know?

**Comment by Dushess** [comment]
Right, next few days i will do it and report here.

**Comment by Dushess** [comment]
So, now i'm testing C&B.
After formed the elevator, all chiseled blocks inside disappears and evevator is very laggy, when any entity is inside and in range of lift width +1 block; plus vertically too.

Maybe whitelist will help.

**Comment by Dushess** [comment]
LT does the same, but no lags and also LTileEntities becomes solid as full block, that collision is not comfy, but still usable (but i can use vanilla blocks with no differences).
As i can say, LTblocks have behavior of common tile entities inside lift, they're moves perfectly with him.

**Comment by Dushess** [comment]
Second time i build only one layer of chiseled blocks as walls (Cabin have 3x3x3 blocks space), and also no lags, that walls also just don't exist while elevator is alive, i can walk trough it.

**Comment by Dushess** [comment]
So, currently, not compatible with LT and C&B, also i will try FMP. 
...
And it works like LittleTiles.

**Comment by Thutmose** [comment]
I suspect their tile entities do some strange things with rendering, which is why they end up invisible, if I get time I will try to look into their renderers and see if I can write some generic support for them.

I can also look into my collision code and see if I can find a good way to account for their collision boxes.

**Comment by Dushess** [comment]
Thank you
