### ISSUE TITLE
Elevator

### ISSUE THREAD

**Issue by ricardosousayt** [Thutmose/Thut#61]
Hello,

I'm trying to create a replicate of Lady Gaga's Joanne World Tour stage in minecraft. I'm using your plugin to create the stage lifts she has on stage. 

She has 3 huge stage lifts together which is what I tried to do. 

I initially sepearated each of the stage lifts in 3 because otherwise it kept saying it's "too big", however, because they are together, I cannot get them to go to the same floor.

Say if I ask lift 1 to go to Floor 4 and lift 2 to go Floor 4, they stay 1 above the other and never on the same level.

**Is there anyway that we can either remove the limit of the elevator floor? Or is there a way to allow it to have 3-4 elevators side by side?**

I've attached a couple of pictures. One of the actual stage in real life, one of what I've done so far in Minecraft.

![mqdefault](https://user-images.githubusercontent.com/31903309/30347886-6a2a0d64-9805-11e7-9ba9-3de4e18ea1cd.jpg)
![lg](https://user-images.githubusercontent.com/31903309/30347885-6a29e6c2-9805-11e7-9a70-6fde08cccac7.png)

**Comment by Thutmose** [comment]
I have never tested having them directly touching each other, I can look into allowing elevators to not collide with each other.

As for the size limits, there are config options in thuttech.cfg to allow larger ones.

**Comment by Thutmose** [comment]
looking into some things, seem elevators do not currently like being placed directly touching each other, this will be fixed for the next release.

**Comment by ricardosousayt** [comment]
Fantastic. Is there an estimated date for the next release?

**Comment by Thutmose** [comment]
hopefully today, pending any rl issues that crop up, looking into best way to get the issue fixed now.

**Comment by Thutmose** [comment]
which minecraft version did you need this for? I can see about releasing that version first.

**Comment by ricardosousayt** [comment]
Minecraft 1.11.2

**Comment by ricardosousayt** [comment]
Let me know once a release for this is sorted. I'm looking forward to it

**Comment by Thutmose** [comment]
the release should be out, for some reason this issue had disappeared for me when I tried to mention it yesterday

**Comment by ricardosousayt** [comment]
Awesome. Any specific links to download? Don't want to download it from somewhere that has the incorrect version

**Comment by Thutmose** [comment]
this is where I upload all of the releases for it: https://minecraft.curseforge.com/projects/thuts-elevators/files version 5.0.3 should fix the issue, let me know how it works for you, I tested with 3 3x1x1 elevators directly adjacent to each other.

**Comment by ricardosousayt** [comment]
You're a genius! It has resolved the issue! However, can't seem to find the file in there with thuttech.cfg that was mentioned to allow the elevators to be larger

**Comment by Thutmose** [comment]
It should be the maxRadius and maxHeight values

**Comment by ricardosousayt** [comment]
The only cfg file I can find is this

Here >> https://imgur.com/a/mPUWf

**Comment by Thutmose** [comment]
There should be thuttech.cfg in the config folder

**Comment by ricardosousayt** [comment]
Do you know the file path for it? I'm looking in winrar. Am I looking in the right place?

**Comment by Thutmose** [comment]
It isn't in the jar, it is in the standard location for mod configs, in the config folder in the Minecraft directory

**Comment by ricardosousayt** [comment]
Found it. I'm an idiot! All sorted. Thanks dude!

**Comment by Thutmose** [comment]
No problem, glad I could help.

**Comment by ricardosousayt** [comment]
Quick question, is there anyway we can make the elevator not take in consideration Air? So I have a lift that is diagonal and needs to fit in the top fitting.

Image here https://imgur.com/a/oq53R

**Comment by Thutmose** [comment]
I am not sure what you mean, but with the fox for the previous issue, you could build one that fits inside another by making it above or below, then moving it into position.

**Comment by ricardosousayt** [comment]
Basically the lower white platform is meant to fit inside of the above platform but it doesn't. That is the highest it goes and then just gives up going higher. 

I've tried making the top 'hood' an elevator to see if it would resolve the issue but it hasn't sadly.

**Comment by Thutmose** [comment]
What is blocking it from going up?

Can you press F3+b then to the screenshot?

**Comment by ricardosousayt** [comment]
I've sorted it by making the hood an elevator and getting the height correct

**Comment by Thutmose** [comment]
ok, let me know if any other issues crop up.
