### ISSUE TITLE
Is this officially supported in 1.12.2?

### ISSUE THREAD

**Issue by P3rf3ctXZer0** [Thutmose/Thut#66]
All your curse releases even latest only 1.12.1 and 1.12 so it officially tested for 1.12.2? I have been playing it on those servers and it functions (mostly) bird seem to fly sideways but otherwise works.

**Comment by Thutmose** [comment]
not done any official testing in 1.12.2 yet, if you want to test it, you can, let me know how it works out

**Comment by P3rf3ctXZer0** [comment]
In that case leave it to me.
