### ISSUE TITLE
[Suggestion] Disguise Controller of Elevator

### ISSUE THREAD

**Issue by D3nnis3n** [Thutmose/Thut#68]
I was really sure the Controller in your Elevator Mod was disguisable ... some time ago ... or i uses another mod before, don't know - but anyway, we really would like to be able to disguise the Controller, so i e.g. take quartz block, right click it with it and it Looks like a quartz block with the numbers on it.

I also knew that for the Elevator blocks itself, so it seems i had used another mod before yours.

**Comment by Thutmose** [comment]
I thought I had added that ability a while ago... let me see what happened to it

**Comment by Thutmose** [comment]
it works, shift right click the bottom face of the controller with the block you want to mask it as.

![image](https://user-images.githubusercontent.com/2363472/31104624-06a0805a-a7ac-11e7-9a78-7279ea5fb7c1.png)

**Comment by D3nnis3n** [comment]
This is working only very inconsistently - out of 50 tries i managed it only once oO

**Comment by D3nnis3n** [comment]
Nah, in nearly all cases it just places the block beneath the Controller - i do not know why. I managed to get it to work once, no idea what i did to manage that.

**Comment by D3nnis3n** [comment]
Okay, it is CTRL-Right Click AND it does only show up after leaving the game and enter it again.

**Comment by D3nnis3n** [comment]
You might want to add this to your manual book :)

**Comment by D3nnis3n** [comment]
Also, this does not work for the elevator block itself, what might be a good idea.

**Comment by Thutmose** [comment]
elevator block itself is never needed to be placed in the world, it is only needed in inventory in survival mode while making an elevator

**Comment by Thutmose** [comment]
it is sneak+right click, default sneak key is shift, so I said shift :D, it does place the block below, I should probably see about making it not do that, and making sure it sends updates if you are on dedicated server.

**Comment by D3nnis3n** [comment]
Eh i hot sneak in shift and still have to use ctrl. I Swear. Control is my
key for sending trade request.

Am 03.10.2017 04:40 schrieb "Thutmose" <notifications@github.com>:

**Comment by D3nnis3n** [comment]
*have sneak on

Sorry, german auto correction. Most probably One of the other mods is
Messing with this. We now know how it Works, and it does with ctrl :)

Am 03.10.2017 04:41 schrieb "Dennis Scholz" <scholzden@gmail.com>:

**Comment by D3nnis3n** [comment]
Yep, there was indeed a mod Messing around with this. I close this issue as it is not valid. (But you should consider adding that disguise mechanic to the book, if it's actually not in there)

**Comment by LachlanArthur** [comment]
I found the only way to consistently disguise the controller is to first right-click (non-sneak) on the bottom face with the block in hand (nothing happens yet), then sneak-right-click on the bottom face again. The block in your hand will be placed _and_ the controller will be disguised at the same time.
