### ISSUE TITLE
Elevator Desync Issues with Advanced Rocketry

### ISSUE THREAD

**Issue by D3nnis3n** [Thutmose/Thut#70]
As you wished, here is a video:
http://minecraft.godsofwar.de/video.mp4

**Comment by D3nnis3n** [comment]
This does ONLY happen when advanced rocketry is installed. Otherwise it works fine.

**Comment by D3nnis3n** [comment]
(And maybe be related to the Economy Mod Issue where this only occurs for one of multiple persons)

I've spoken with another developer. He told me to mention the doors that are open (as the elevator in fact is on the right floor) and that when i relog the elevator is in the right place. He said that is a client desync happening.

Also in some rare other occasions the elevator just goes down to the deepest point it can (even below his starting point!) get and sticks there unmoveable. I couldn't tape that yet. I'll try to.

**Comment by D3nnis3n** [comment]
More Information:
When you remove Advanced Rocketry from the Server, but not from the client you cannot enter Elevators anymore (invisible wall), and if you bug yourself into it, you will fall through its floor.

**Comment by Thutmose** [comment]
I have managed to replicate this finally, now I will see about trying to find out why and what is going on.

**Comment by Thutmose** [comment]
I have confirmed that it is somehow related to the gravity handler in advanced rocketry, however this looks like a fix that should be done on my end, as the gravity handler in AR isn't doing anything strange that I shouldn't account fot.

**Comment by Thutmose** [comment]
or maybe not, further testing seems to indicate there is something else interacting badly here...

**Comment by Thutmose** [comment]
Issue has been narrowed down to an oversight in the elevator itself's movement code, this should be a fairly easy fix now.  In the mean time however I am going over some other code for the elevator to try to add better support for some of the newer features in minecraft wrt block states.

**Comment by D3nnis3n** [comment]
I'm happy you finally could reproduce my issue :D

**Comment by Thutmose** [comment]
see if 6.0.6.1 for thuttech fixes it

**Comment by D3nnis3n** [comment]
That supposedly fixed the issue. Great. I'll see if it works with Sponge now or try to get a console log.

**Comment by Thutmose** [comment]
Also update thutcore, it makes some tweaks to collision box stuff for the elevators

**Comment by D3nnis3n** [comment]
I did. Unfortunately, the sponge issue persits.
