### ISSUE TITLE
Elevator Controller Block Reskin Crash

### ISSUE THREAD

**Issue by Dystinct** [Thutmose/Thut#72]
After re-skinning the Elevator Controller Block with whatever block (including Vanilla blocks) caused the client (on a server) who attempted to break the block immediately crash out of the game entirely.

[crash-2017-10-13_01.17.31-client.txt](https://github.com/Thutmose/Thut/files/1396846/crash-2017-10-13_01.17.31-client.txt)

**Comment by Thutmose** [comment]
is the server itself affected, or just the client?

**Comment by Dystinct** [comment]
Just the client.

**Comment by Thutmose** [comment]
ok, I will get this looked into, hopefully will be able to get a fix pushed out shortly.

**Comment by Dystinct** [comment]
Thanks :)

**Comment by Thutmose** [comment]
unzip the jar from here, see if it fixes it, currently have some other testing stuff running so can't check it right now (will be able to in about 20-30 minutes)
[thuttech-6.0.5.2.jar.zip](https://github.com/Thutmose/Thut/files/1396903/thuttech-6.0.5.2.jar.zip)

it was put in a zip so github would allow me to send via comment

**Comment by Thutmose** [comment]
the fix should only be needed on the client, should allow you to connect to the server with that version

**Comment by Thutmose** [comment]
seems there is also a server side version of the issue, though it doesn't result in a crash, working on testing fixes now

**Comment by Thutmose** [comment]
This is now fixed in version 6.0.6.  It will be available here whenever it is approved by curseforge:

https://minecraft.curseforge.com/projects/thuts-elevators/files/2492118
