### ISSUE TITLE
[ELEVATOR] Distance issue

### ISSUE THREAD

**Issue by ricardosousayt** [Thutmose/Thut#73]
Hello,

I'm using your mod on minecraft 1.12.2 and it seems all working fine, except for me only being able to view the elevators when I'm close to the them. If I'm a bit further away or move suddenly they disappear and only re-appear once I'm close to them. 

Images here:
Close -> https://imgur.com/wJ5FdWU
Away -> https://imgur.com/VVgNZkH

I've changed a few settings on my minecraft to see if it would resolve, but no luck. I've also tried with optifine and without it. Either way still happens.

Can you assist?

**Comment by Thutmose** [comment]
This seems like it might be an issue with the render distance on the elevator, though that image doesn't make it look far enough away for it to not render... I will look into it and see if I can find what is going on.

**Comment by ricardosousayt** [comment]
Thank you!

**Comment by Thutmose** [comment]
[thuttech-6.0.7.jar.zip](https://github.com/Thutmose/Thut/files/1412094/thuttech-6.0.7.jar.zip)
test this and see if it works (unzip the jar from the zip)

I will be afk fora  bit, so don't have time to test myself, I can see about getting it tested when I get back.

**Comment by ricardosousayt** [comment]
Tested and still does the same

**Comment by Thutmose** [comment]
Ok, I should be back at PC in 30mins or an hour, I can look into things then, is this on single player or on a server?

**Comment by ricardosousayt** [comment]
It's on single player

**Comment by ricardosousayt** [comment]
Thanks

**Comment by Thutmose** [comment]
so I have definitely confirmed that this still occurs, and I am looking into possible causes/fixes

**Comment by ricardosousayt** [comment]
Awesome. Let me know once you've gotten something

**Comment by Thutmose** [comment]
[thuttech-6.0.7.jar.zip](https://github.com/Thutmose/Thut/files/1412562/thuttech-6.0.7.jar.zip)
try this one (jar is named the same as previous, but has a minor change internally)

**Comment by ricardosousayt** [comment]
All perfect. Tested it several different ways and it seems to be working!

**Comment by ricardosousayt** [comment]
Thank you! :)

**Comment by Thutmose** [comment]
No problem, I will see about releasing that as a new version whenever I have time to, possibly sometime later tonight or tomorrow
