### ISSUE TITLE
startup warnings with thutperms/essentials

### ISSUE THREAD

**Issue by smmmadden** [Thutmose/Thut#75]
Not sure if this is where you want to report issues.  But I am using your permissions mod so that I can setup player access as needed.  Tried a couple others and the only one that seems to work smoothly is yours. :-)

Mods:
- Pokecube Core: 6.23.3
- Pokecube Revival (if applicable): 6.13.2
- Pokecube Mobs (if applicable): 4.1.2
- thut_bling: 2.0.1
- thut_wearables: 3.1.2
- thut_core: 5.11.7
- thutpermissions: 2.0.0
- thutessentials-2.1.3
- dynmap-2.6-beta-1-forge-1.12
- worldedit-forge-mc1.12-6.1.8-dist
- Minecraft: 1.12.2
- Forge: 1.12.2 (1.12.2-14.23.0.2528)

During start - I can see the commands trying to get registered, but having issues with case sensitivity.
https://pastebin.com/9VgMZAYR
Everything appears to be fine, just seeing warnings like the code expects lower case but somewhere we are passing in mixed cased commands.

**Comment by Thutmose** [comment]
That is caused by sponge messing around with command names, you can probably ignore it unless it is making commands not work at all, those warnings do not occur without sponge.
