### ISSUE TITLE
Doors not Opening/Closing

### ISSUE THREAD

**Issue by Dickovski** [Thutmose/Thut#76]
When I first used Thus's elevator this worked very nicely (pre-1.10.2, can't remember what version).  Now in 1.10.2 the feature does not appear to work, or am I missing something.  The rest of the mod seems to work fine.  Perhaps a feature to hide floors that are not used would be nice.  A very clever mod!

**Comment by Thutmose** [comment]
how do you have the doors setup? the controller emits a redstone signal when the elevator is at that floor, so if you don't have the door touching a controller, or otherwise send a redstone signal from controller to door, it won't open doors

**Comment by Dickovski** [comment]
Thanks for the suggestion.  I hadn't placed the control bloke next to the door blocks, I had them placed one away.  It now works fine.  A great mod and this version works very smoothly.

**Comment by Thutmose** [comment]
No problem, you can also link multiple controllers per floor if doors and controllers need to be in different locations, though I don't think I have released the bug fixes for some redstone stuff for some casesvof that for 1.10.2 yet
