### ISSUE TITLE
crash upon startup (1.10.2)2041

### ISSUE THREAD

**Issue by SDUBZ** [Thutmose/Thut#8]
crashlog:
[crash-2016-07-30_11.10.32-client.txt](https://github.com/Thutmose/Thut/files/391625/crash-2016-07-30_11.10.32-client.txt)
#### What happens:

crashes on loadup
#### What you expected to happen:

to load successfully
#### Steps to reproduce:

1.have forge 1.10.2-2041
2.press play game
3.
...

---
#### Affected Versions (Do _not_ use "latest"):
- Thut Core:3.2.3
- Thut's Elevators (If Applicable):3.0.6
- Forge:1.10.2-2041

**Comment by Thutmose** [comment]
hmm, forge must have changed something in the latest version... I will get this fixed asap.

**Comment by kreezxil** [comment]
confirmed

Issue:  thutcore{3.2.3} crashes dedicated Forge 1.10.2 build 2041 on startup

crash report:
https://gist.github.com/ed047ad5d8b2b9e708671cef8abe3159

fml server latest:
https://gist.github.com/4fecb23e35b3b901d23da9a21db65c02

**Comment by Thutmose** [comment]
I am setting up 1.10.2 development for those mods now, will hopefully get this fixed shortly, until now I have just been developing this for 1.9.4 and it has been working fine in 1.10+

**Comment by kreezxil** [comment]
that's mainly because Forge didn't touch any of the core classes you were using up until now. You can chat on my chat server so as to not needlessly clutter your issues if you want to.

**Comment by Thutmose** [comment]
Uploaded 4.0.0 for ThutCore to curse. it fixes this issue.
