### ISSUE TITLE
Elevator call buttons aren't displayed correctly

### ISSUE THREAD

**Issue by YonicDev** [Thutmose/Thut#83]
When right-clicking the top of the Controller block while crouching, there's nothing that indicates that it's been set to a call button.

I've bound crouching to 'F', so just in case I've tried with shift, but the effect is the same.
Probably not a conflict since it's the only mod I have beside Worldedit.

**Comment by Thutmose** [comment]
1.12.2 the call feature changed to per side, now you need to shift right click the face you want to be a call face with an un-linked device linker

**Comment by YonicDev** [comment]
I'd suggest updating the in-game manual to reflect the change.

Also, the call button is only displayed correctly when the set of buttons before converting it to a call button is the first one (1 to 16). In the case of other sets of buttons it won't display the button properly.

**Comment by Thutmose** [comment]
I will look into that then, I will also see about checking the manual

**Comment by Thutmose** [comment]
this should be fixed now

**Comment by suntzu243** [comment]
I can't get the block to become a call controller at all, to the best of my knowledge. Maybe there's something I don't understand. Do two controllers need to be attached to the elevator (one a call and one a normal controller) or is it intended to be a single block?

**Comment by Thutmose** [comment]
try updating the version, the new update should fix quite a few related issues
