### ISSUE TITLE
[1.12.2] Falling through floor while traveling multiple floors on descent

### ISSUE THREAD

**Issue by themechman** [Thutmose/Thut#84]
thutcore-5.13.0
thuttech-6.0.10
forge 14.23.1.2555

So I am running into an odd problem that does not always occur.

During descents from upper floors, players are being dropped through the elevator floors. The floors need a considerable distance, but this is what happens.

Floors 3 to 2, no problem.
Floors 2 to 1, no problem.
Floor 3 to 1 direct, and I fall through

Distance between floors is 7-8 blocks.

Sometimes after doing it 2-3 times it stops. Disconnect and reconnect and it happens all over again. If I stare at the floor as soon as it starts moving, doesnt happen. If I stare at the control panel when I press the button (dont move anything), i fall through.

**Comment by Thutmose** [comment]
I have also noticed this on a server I play on, but have still yet to get it to occur in my development environment, I will do more looking into it.

**Comment by mainrs** [comment]
It seems to occur if the server lags behind ticks.

**Comment by Thutmose** [comment]
hmm, I can see if I can get some lagginess in my development environment to test this

**Comment by mainrs** [comment]
It mostly happens on multiplayer though. Singleplayer is almost always fine for me.

**Comment by Thutmose** [comment]
currently working on this, also fixing some of the bounciness on the elevators in the mean time.

**Comment by Thutmose** [comment]
This should be fixed in thuttech 6.0.11 and thutcore 5.14.3

**Comment by themechman** [comment]
Thank you! Hope you have a safe new year!

**Comment by mainrs** [comment]
Wow, no idea what you actually did there with the collision boxes (that piece of code looks complicated as hell) but it works perfectly now. Even the strage stuttering is gone :smile:
Great job! Thanks you ^^

**Comment by Thutmose** [comment]
I took the various checks I was doing before, and split them up so I could manage them better, then I more properly dealt with the various cases of collision checking.

I also implemented some hitbox merging that I had partially implemented before, which reduces the number of boxes to check against
