### ISSUE TITLE
OpenComputers API: isReady method

### ISSUE THREAD

**Issue by mainrs** [Thutmose/Thut#87]
A method similar to the old `isReady()` call would be nice. That way people can check if the elevator has already arrived at the destination (just waiting for true).

**Comment by Thutmose** [comment]
you can already somewhat do this with the getYValue, to tell if the elevator is at the yValue of the floor, but I can add this method as well, which will return true if the elevator isnt moving

**Comment by mainrs** [comment]
that woudl be awesome! Just saw that there are a lot more methods supported through opencopmputers. Is there a way I can update the docs? the ones on opencomputers are outdated and the curseforge page only mentions 4 out of 9 total functions

**Comment by Thutmose** [comment]
I should probably update the curseforge page one, not sure about the opencomputers one

**Comment by Thutmose** [comment]
the isReady is added in 6.0.11

**Comment by Thutmose** [comment]
updated the curseforge page as well to include the methods currently in
