### ISSUE TITLE
Controller Block inside elevator

### ISSUE THREAD

**Issue by schmarcel02** [Thutmose/Thut#88]
I tried to place an "Elevator Controller Block" inside an elevator,sn like it is described in the manual. I built the elevator and included the Controller Block. I activated the face as stated in the maual. After creating the elevator with the device linker, i can't interact with the controller anymore. The elevator itself is working perfectly.
![thut2](https://user-images.githubusercontent.com/33518721/34582620-d6033388-f194-11e7-94af-92810036b83d.PNG)

![thut1](https://user-images.githubusercontent.com/33518721/34582602-c097da1c-f194-11e7-9ef6-8555606f39b4.PNG)

**Comment by Thutmose** [comment]
I will have to look into this, I suspect some of the fixes to a bunch of collision related bugs may have disabled that feature, so I will need to fix it

**Comment by Jschmuck2** [comment]
Chiming in to note the same issue here -- 1.12

**Comment by Thutmose** [comment]
this fix will be reelased as version 6.0.14
