### ISSUE TITLE
Crash making elevator with fences/glass panes/ iron bars

### ISSUE THREAD

**Issue by MechWarrior99** [Thutmose/Thut#9]
#### Issue Description:

When trying to form a elevator that has fences, glass panes, or iron bars in it, the game will crash and you will be unable to rejoin the world.
#### What happens:

Game crashes, and unable to rejoin.
#### What you expected to happen:

To form a working elevator. And not to crash.
#### Steps to reproduce:
1. Place an elevator base. And expand it to be at least 3x2x3
2. Place fences, glass panes, or iron bars as the walls of the elevator
3. Try to form the elevator
4. Crash

---
#### Affected Versions (Do _not_ use "latest"):
- Thut Core: 1.10.2-4.0.0
- Thut's Elevators: 3.0.7
- Forge: 1.10.2-12.18.1.2043

**Comment by Thutmose** [comment]
can you post the crash report?

**Comment by MechWarrior99** [comment]
I got the crash wrong, it is when you touch a elevator that has iron bars, fences, or glass panes in it http://pastebin.com/5gbKNE2S

**Comment by Thutmose** [comment]
I will see about getting that fixed shortly.

**Comment by Thutmose** [comment]
This is fixed in 3.0.9, which I just uploaded.  Note that they do not currently render correctly, and do not have collision, I will probably see about trying to fix that eventually.
