### ISSUE TITLE
Rapid hunger loss standing on elevator

### ISSUE THREAD

**Issue by mctom987** [Thutmose/Thut#90]
Rapid hunger loss, even if elevator is not moving. Elevator is 3x3x1.

Core v5.15.2
Tech v6.0.12

Noticed in FTB Revelation v.1.3.0

**Comment by Thutmose** [comment]
not sure why, this is probably something vanilla related to swimming...

**Comment by Thutmose** [comment]
I found the problem, and am trying to decide on best way to fix it, it seems vanilla think the player is jumping when they are standing on the elevator, and that is what is using up the hunger

**Comment by Thutmose** [comment]
The fix for this is in ThutCore 5.15.3
