### ISSUE TITLE
Locked to elevator create mode

### ISSUE THREAD

**Issue by mctom987** [Thutmose/Thut#91]
Accidentally clicking a block before Device Linker is bound locks it to creating an elevator, with no means of escape. I tried clicking other blocks, but only tries to size the elevator as clicked. Even clicking an existing elevator (to bind it) did not release from create mode. I tried dropping it, logging in and out, and ultimately just ended up crafting it into a manual to get it unstuck.

First failure should reset the mode, or another method of cancelling should be provided.

Core v5.15.2
Tech v6.0.12

Noticed in FTB Revelation v.1.3.0

**Comment by Thutmose** [comment]
Right, I need to make it so you can craft it with itself to cancel

**Comment by Thutmose** [comment]
this will be out in 6.0.13, whenever it gets approved on curseforge.
