### ISSUE TITLE
[REQUEST] Compatibility with ComputerCraft/CC:Tweaked

### ISSUE THREAD

**Issue by vico93** [Thutmose/Thut#94]
Since [ComputerCraft](https://github.com/dan200/ComputerCraft) [became Open Source a while ago](http://www.computercraft.info/2017/05/01/computercraft-is-now-open-source/) i think a good thing to add is a compatibility layer similar to the OpenComputers one.
I prefer CC over OC due to easyiness of use and more integration into vanilla look and feel.

Anyway thanks a lot for reading!

**Comment by Qonsyuma** [comment]
Was going to request this too, but seems like someone else had this idea already a long time ago :)
I'd love to see this, pretty useful for adding some extra fancy stuff to your elevators.

**Comment by vico93** [comment]
Just FYI, since dan200 stopped working on the original mod (althrough he released the source), I recommend, if dev want to make it, to target one of the more regularly updated forks, such as [CC: Tweaked](https://github.com/SquidDev-CC/CC-Tweaked) ([CurseForge](https://www.curseforge.com/minecraft/mc-mods/cc-tweaked)).
