### ISSUE TITLE
Fall through elevator with Silent Gem flight

### ISSUE THREAD

**Issue by TookUrSweetRoll** [Thutmose/Thut#95]
With Silent Gems flight equipped, I glitch through the elevator, but only going down.  The ride up is smooth and enjoyable.  Not sure if it's you or him, I will post to both.  You can close this without responding, just wanted to make you aware of the (potential) issue.  Great mod.

thutcore 5.13.2
thuttech 6.0.10
silentlib 2.16-97
silentgems 5.11-250

**Comment by Thutmose** [comment]
Can you confirm whether this still occurs with recent versions?
