### ISSUE TITLE
Lighting not working properly in elevator car

### ISSUE THREAD

**Issue by JimmyAllnighter** [Thutmose/Thut#98]
Lighting does not function at all in an elevator car. The screenshot below shows this (the light in the elevator shaft is shining through the door from the current level). It would be great if lights could function similarly to Optifine's Dynamic Lighting option :)

![2018-02-10_01 34 35](https://user-images.githubusercontent.com/36003168/36035770-9cf79e90-0e03-11e8-8746-b7d157560066.png)

**Comment by Thutmose** [comment]
the problem with lighting in elevators, is that vanilla lighting is block based, and elevators are entities.  This means that via vanilla methods, it is impossible for an elevator itself to emit light.  One way to get this effect, will be to make fake light blocks which are placed and removed as the elevator moves, which can be a rather low-performance solution.  The other way is to attempt to edit the lighting arrays directly, which also has performance issues, as well as causing compatibility issues and some glitchiness if not done exactly correctly, this is what optifine does client side

**Comment by JimmyAllnighter** [comment]
Ah true. Framerates are already pretty dodgy on FTB Revelation. I wasn't too sure how that lighting really worked with Optifine in the first place, just that it looked pretty neat. I guess the best solution for players would be to just add lighting in the elevator shaft. Thanks for looking into this.
